### ISSUE TITLE
Remove blank space at the bottom of the editor

### ISSUE THREAD

**Issue by machitgarha** [pulsar-edit/pulsar#439] opened 2023-03-24 06:20 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

There is an annoying blank space at the bottom of the editor:

![image](https://user-images.githubusercontent.com/14151550/227440709-299903e8-1a9d-4097-9453-4b175194c0c1.png)

When I enter new lines, its size gets smaller until being collapsed.

BTW, this bug should be considered minor.

### Pulsar version

1.103.0

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Fedora 37 WS

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open the editor.
2. Open a new tab.

**Comment by confused-Techie** [comment] 2023-03-24 06:30
I appreciate the OS version and details. But do you have any packages installed? I've never seen or heard of this behavior, (but admittedly do have minor experience with Pulsar on Linux)

Here's what we would expect to be seen on a new tab

![image](https://user-images.githubusercontent.com/26921489/227442829-46fe5c65-9210-449a-9b81-34b2d8915910.png)

And this is on Pulsar v1.103.2023031910 fyi

**Comment by machitgarha** [comment] 2023-03-24 06:43
I disabled all packages and tried in safe mode, but no luck.

**Comment by machitgarha** [comment] 2023-03-24 06:47
Ah, sorry. It was my own bad styling... :)

However, isn't that still counted as a bug? I just set my theme to Solarized Dark, and it looks like this:

![image](https://user-images.githubusercontent.com/14151550/227445945-a0031b67-bc8f-4706-8804-7fe3e0735f17.png)

The blank space is still there, but not really visible.

**Comment by confused-Techie** [comment] 2023-03-24 06:57
@machitgarha Do you mind sharing your custom styling?

> isn't that still counted as a bug?

It depends. Pulsar is the Hyper-Hackable text editor after all. That means if you want blank bars at the bottom of your screen, all the power to you. Pulsar lets you do essentially whatever you want. Including this. It being a bug depends on if your custom styling is intending for this to happen or if it's some side effect. So without seeing your custom stylesheet there's really no way for me to determine or recreate this

But thanks for getting back to me!

**Comment by machitgarha** [comment] 2023-03-24 07:03
Pulsar automatically ported my configurations from Atom, and my styling was there. So it was unintentional.

This is my styling:

```css
.item-views > atom-text-editor.editor {
    .syntax--type,
    .syntax--parameter,
    .syntax--class {
        font-style: normal;
    }

    background-color: inherit;
    .gutter {
        background-color: #0f0f0f;
    }
    div.scroll-view div.lines {
        background-color: #0f0f0f;
    }
}
```

**Comment by confused-Techie** [comment] 2023-03-24 07:28
@machitgarha Oh interesting, I didn't realize it had imported it from Atom. Did this behavior happen on Atom? And if not, do you know what version you were on last?

But I'll go ahead and test out your provided stylesheet and see if I can replicate this issue. 
Which to confirm it looks like you were using One Dark initially correct?

**Comment by confused-Techie** [comment] 2023-03-24 07:31
Also interesting, I can't quite replicate this on Windows 22H2 with a new Pulsar project open.

![image](https://user-images.githubusercontent.com/26921489/227454049-30d46f58-e9af-4f5f-be64-296c4a006eae.png)

I'll go ahead and ping our Linux users and see if anyone is able to recreate this behavior

**Comment by machitgarha** [comment] 2023-03-24 07:35
@confused-Techie, I think the latest Atom version I didn't have this problem was 1.60.0 and I'm still using it. However, I remember the bug existed in Atom 1.63.0, which is the latest release. So, not really Pulsar's fault.

And about the look... That's strange.

**Comment by confused-Techie** [comment] 2023-03-24 07:39
So the Atom 1.63.x and our first release both bumped the version of Electron. But Atom ended up pulling back that release (for other reasons).

So it seems that this issue could stem from that, but might not be the stylesheet itself. 

But you mentioned it seemed to be that, have you removed the custom stylesheet to see the issue go away? Or if you remove it, does the issue remain?

Do you have a custom init script at all set from the old Atom days maybe? Any errors being reported in the DevTools that might lead to the source of the issue

**Comment by machitgarha** [comment] 2023-03-24 07:50
@confused-Techie, look at [this image](https://github.com/pulsar-edit/pulsar/issues/439#issuecomment-1482332805). The left pane used for line numbering is not continued to the very bottom of the page. The blank space should still be there, but because it's better styled, it's not bad on the eyes. So I think this can be counted as a bug, if reproducable.

I'm not sure whether the issue first appeared in Atom version 1.63.0, just a guess.

BTW, I can live without the style, and even now I commented it (as my default look of theme seems to be better). :)

**Comment by Spiker985** [comment] 2023-03-24 13:54
Arch Linux, xfce4, one-dark
![image](https://user-images.githubusercontent.com/7829451/227538548-a9f0c9de-dffb-4f67-acd1-2ba823ba9d62.png)

If you open Dev Tools (Ctrl + Shift + I), use the Inspect tool (Ctrl + Shift + C), click on the blank space or try to expand the elements - what does it say the element is?

**Comment by Pysis868** [comment] 2023-03-24 14:24
![2023-03-24_10-17-58](https://user-images.githubusercontent.com/1408565/227550713-56000143-1ffd-43dd-a3c9-02363ac82482.png)
`/usr/bin/pulsar` -> `/opt/Pulsar/pulsar`
Just installed the RPM 1.103.2023032401 for this test.
Was not occurring with 1.102 from the repos earlier either.
No style/edtior customizations, some packages installed.
```
⋊> neofetch --stdout distro kernel wm theme icons
distro: Fedora release 37 (Thirty Seven) x86_64 
kernel: 6.1.18-200.fc37.x86_64 
wm: i3 
theme: Adwaita [GTK2], Adwaita-dark [GTK3] 
icons: Adwaita [GTK2], Adwaita-dark [GTK3]
```
Workstation (WS), + GNOME and Xorg.

**Comment by machitgarha** [comment] 2023-03-24 16:36
@Spiker985, it's an empty space inside a `div.scroll-view`:

https://user-images.githubusercontent.com/14151550/227586552-a40d958b-ee6f-4035-a19c-3cd399be049f.mp4

**Comment by Spiker985** [comment] 2023-03-24 17:02
You checked the "recreated in safe mode" checkbox, so I can assume that's accurate, yes?

It seems like the margins or something are way off?

I am curious, if you rename your `~/.pulsar` folder and then relaunch, does this still occur?

**Comment by machitgarha** [comment] 2023-03-24 17:15
@Spiker985, I've reproduced in safe mode, yes.

> It seems like the margins or something are way off?

Kind of.

> I am curious, if you rename your ~/.pulsar folder and then relaunch, does this still occur?

Opening in safe mode is not enough? It shouldn't make a difference, should it?

**Comment by Spiker985** [comment] 2023-03-24 17:29
> Opening in safe mode is not enough? It shouldn't make a difference, should it?

Well, it should be, but unfortunately, there have been others who have had their problem resolved by renaming their pulsar folders, due to either misconfigurations on their parts or due to leftovers from packages

It's just one of those things that shouldn't be necessary, but does give definite answers

**Comment by machitgarha** [comment] 2023-03-24 17:43
@Spiker985, it did the trick! The problem is fixed! Thanks!

So, what now? What's really the root of the problem?

**Comment by Spiker985** [comment] 2023-03-24 18:00
> @Spiker985, it did the trick! The problem is fixed! Thanks!
> 
> So, what now? What's really the root of the problem?

Ironically enough, now would be the most time consuming process - determining root cause.

One of the best ways to go about trying to find the problem would be to put back files/folders until the problem resurfaces.

You can use something known as _binary searching_ to accomplish this: copy half the packages back into `.pulsar/packages`, relaunch the editor.

If the problem arises, remove half of the packages you just put in, relaunch. Continue until you're left with the package.

The other thing you can do, which is shorter, is don't copy any of the packages initially, and just replace the `config`, `github`, `init`, `keymap`, `snippets` and `styles` files back into .pulsar - see if the mere existence of any of those files causes the problem.

Normally, the problem seems to be contained within the `config` or `init` files - but who really knows.

Another alternative, would be to use a comparison program like [Meld](https://meldmerge.org/) to compare the directories and file contents in order to gain a more "complete" view

**Comment by Spiker985** [comment] 2023-03-24 19:19
> @Spiker985, figured out the root of problem. When you enable "Scroll Past End" option in Editor Settings, this space starts to appear (i.e. related to `config.cson`).
> 
> Just tried with a clean Pulsar config.

Interesting, enabling this on my side requires me to actually have content at the bottom towards the edge of the screen in order to scroll past it. I can't scroll infinitely on just line 1 :thinking:

**Comment by machitgarha** [comment] 2023-03-24 19:33
> > @Spiker985, figured out the root of problem. When you enable "Scroll Past End" option in Editor Settings, this space starts to appear (i.e. related to `config.cson`).
> > Just tried with a clean Pulsar config.
> 
> Interesting, enabling this on my side requires me to actually have content at the bottom towards the edge of the screen in order to scroll past it. I can't scroll infinitely on just line 1 :thinking:

I didn't understand. When you have only one line in the editor, the view is not scrollable.

**Comment by m1ga** [comment] 2023-03-24 19:33
> @m1ga, it's not related to light or dark themes. If the background-color of the parent div is different from at least one of its children elements, then it's visible.

oh correct. Wanted to write "One Dark". But the rest is still valid :smile:

**Comment by Spiker985** [comment] 2023-04-20 08:05
Did we confirm this was a combination of the Scroll Past End option, and a possibly misconfigured theme?

**Closed** 2023-04-20 14:44 UTC
Labels: bug
