### ISSUE TITLE
Flatpak update deletes all manually installed packages

### ISSUE THREAD

**Issue by jberkus** [pulsar-edit/pulsar#665] opened 2023-08-07 18:19 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

1. I was running a prior version of Pulsar installed via Flatpak
2. I have flatpak set to auto-upgrade from Flathub
3. It upgraded to 1.107.1 today
4. The upgraded Pulsar had none of the packages I had manually installed.  Only the default packages were available, as if it was a brand-new install.

For example, I'd installed vk-terminal from the Packages GUI, and it was gone.

### Pulsar version

1.107.1

### Which OS does this happen on?

❓ Other(Please specify in the OS details field below)

### OS details

Fedora Silverblue 36, installed via Flatpak

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Install older Pulsar via flatpak
2. Intall several community packages
3. Upgrade the flatpak

### Additional Information:

This did not previously happen with the Atom flatpak, so the packaging for Pulsar is different somehow?

**Comment by savetheclocktower** [comment] 2023-08-07 18:32
Have the contents of your `~/.pulsar` directory changed, or the contents of `~/.pulsar/packages`?

**Comment by jberkus** [comment] 2023-08-07 18:52
Interesting.  They haven't, what's happening is that the new version isn't reading from ~/.pulsar.  As in: the list of packages in ~/.pulsar/packages doesn't match what I see through the interface, and if I install a new package, it doesn't appear in ~/.pulsar/packages

**Comment by savetheclocktower** [comment] 2023-08-07 18:54
Can you open the developer console? (On my OS, it's under View -> Developer -> Toggle Developer Tools, or I think the key combo might be <kbd>Ctrl + Shift + I</kbd> on your platform.)

If you can, go to the Console tab and run

```js
process.env['ATOM_HOME']
```

and report what it says.

**Comment by jberkus** [comment] 2023-08-07 18:57
Hmmm.  Where should the console appear when I do that?  Because I'm trying Toggle Developer Tools, and nothing seems to happen.

**Comment by savetheclocktower** [comment] 2023-08-07 19:00
It should appear immediately in a sidebar. You'll know when it shows up.

Try closing Pulsar altogether, then running it from the command line with the `--no-sandbox` flag. Then try toggling the Developer Tools again.

**Comment by jberkus** [comment] 2023-08-07 19:10
--no-sandbox isn't a flatpak option.  I tried launching it from the command line, though, just to see if it was being run with --sandbox by gnome.  No change.

Here's the error stream from command-line launch:

```
Gtk-Message: 12:08:35.680: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:08:35.682: Failed to load module "canberra-gtk-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.yuUgaW'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(Use `exe --trace-warnings ...` to show where the warning was created)
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.pCFPXz'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.PoGrYR'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.2SVhaX'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/app/Pulsar/resources/app.asar.unpacked/node_modules/spellchecker/build/Release/spellchecker.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.GsgUKd'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.iKWOas'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.LwGWZP'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.1fatYn'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.cMXzUI'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.CqSlyA'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.5oXE9d'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.bzuUv9'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.FjpUlv'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.4TE2bG'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.tPt1wY'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.xRCR0r'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.kQZsvy'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.3RHGc0'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/app/Pulsar/resources/app.asar.unpacked/node_modules/tree-sitter-bash/build/Release/tree_sitter_bash_binding.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:77) Electron: Loading non-context-aware native module in renderer: '/var/tmp/.org.chromium.Chromium.i8RK06'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

**Comment by savetheclocktower** [comment] 2023-08-07 19:13
What exactly did you run to start Pulsar to get that output? Just want to make sure we're on the same page.

**Comment by jberkus** [comment] 2023-08-07 19:28
flatpak run dev.pulsar_edit.Pulsar

**Comment by savetheclocktower** [comment] 2023-08-07 19:39
Pulsar has a command-line version just called `pulsar`. I don't remember if you have to do anything to add it to your `PATH`, but that's what you'd need to add the `--no-sandbox` flag to.

(I promise that there are other people on the project that are more familiar with Flatpak than I am, so don't give up if the two of us can't figure this out just yet. :-))

**Comment by jberkus** [comment] 2023-08-07 19:54
Aha!  No, all you had to tell me was that that was a pulsar flag, and not a flatpak flag.*

Here's where it's storing user data now:

```
"/var/home/jberkus/.var/app/dev.pulsar_edit.Pulsar/data"
```

... so somehow, between my prior Flatpak version, and the current one, someone moved the config storage location from `~/.pulsar/` to `~.var/app/dev.Pulsar/data`.   Which is probably the correct location, long-term, but maybe users need to be warned.

**Comment by savetheclocktower** [comment] 2023-08-07 19:58
OK, so I have no clue if this is intended behavior. I want to say that there have been some changes with Flatpak recently, so this might've been foreseeable, but I can't find a PR or an issue for it.

@confused-Techie, do you remember? I know we don't officially support Flatpak yet, but I'm wondering what we should tell people about this behavior change.

**Comment by Spiker985** [comment] 2023-08-07 20:22
I do believe that the storage location change was intended.

We don't officially support the flatpak distribution, however, per flatpak's own guidelines (and due the the fact that flatpak installations are meant to be sandboxed) packages aren't meant to interact with your home directory, nor anywhere else

**Comment by jberkus** [comment] 2023-08-07 20:41
Well, for posterity, this worked:

`cp -p -r * ~/.var/app/dev.pulsar_edit.Pulsar/data/packages/`

Leaving this issue open until y'all decide if any user notifications are warranted.  You can close it when you're done with that.

**Comment by confused-Techie** [comment] 2023-08-07 23:36
I think this relates to [this issue](https://github.com/flathub/dev.pulsar_edit.Pulsar/issues/17).

Changes over on the Flatpak repo have changed where data is loaded from.

This doesn't look to be a change made by us. As Flatpak is entirely community supported, and has no official support at this time.

Because Flatpak isn't officially supported I don't think it's on us to communicate this change. As this change wasn't communicated at all to us previously. So in the future we have zero way to stay on top of it, besides the fact that I make sure I'm notified of everything going on over on that repo.

So this change seems intentional, as per [this PR](https://github.com/flathub/dev.pulsar_edit.Pulsar/pull/15). So ideally this is the only time this would ever occur, and I'm sorry it took you by surprise. But really, it also took us by surprise

**Comment by savetheclocktower** [comment] 2023-08-07 23:51
Ah, OK. So we can refer people to that issue if this comes up again. Thanks!

**Closed** 2023-08-07 23:52 UTC
Labels: bug
