### ISSUE TITLE
PackageUpdatesStatusView is not a constructor

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#556] opened 2023-05-23 15:35 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

error has occur every time after Pulsar start

### Pulsar version

1.105.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Run Pulsar

### Additional Information:

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/caf16ba2-f0a3-430d-9de9-bcc4eb0a0430)

**Comment by confused-Techie** [comment] 2023-06-18 18:17
Sorry for the lag on this one, thanks a ton for reporting this issue!

**Comment by confused-Techie** [comment] 2023-06-18 18:23
I will say I'm having trouble reproducing this one. But I think I do see something that might cause some weirdness. I'll make a PR for it and hopefully you can test it out

**Comment by asiloisad** [comment] 2023-06-18 18:28
hmm, It's intresting. I get this error every time after pulsar open (with/withour --safe) at two diffrent windows 10x64 pc's.

**Comment by asiloisad** [comment] 2023-06-24 11:12
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/eb1bc8ef-ca23-4475-8806-7cb6e3883253)

**Comment by confused-Techie** [comment] 2023-06-24 20:22
Very interesting it's even getting picked up for you as being wrong. Because right above there the file `./package-updates-status-view.js` is definitely exporting a class that is a constructor. And it's not being overridden anywhere in that file. So it should be correct, but I'll take a look at it, that's very interesting

**Comment by asiloisad** [comment] 2023-06-24 22:01
I have investigate it more as you say you cant recreate it and it's strage. I have create new `.pulsar` dir, then copy all settings (config, init, keymap, snippets, stylesheet), copy all packages and ... error has disapear. Everything looks like before, but without error. For test purpose then I have restore old `.pulsar` and error has appear again. I don't what is going on, but recreating `.pulsar` dir resolve problem. I think we can close the issue or I can assist with investigation the problem 👍

**Comment by asiloisad** [comment] 2023-06-24 22:05
I have investigate more and the problem was a dir `compile-cache`. It look like some old sh!t has been compiled and pulled my config dir. I have deleted it in my old `.pulsar` and problem disappeared.

**Comment by confused-Techie** [comment] 2023-06-24 22:08
@asiloisad That's awesome!

How weird to see this come from an old compile cache. But something must have just gone wrong during the transition from Atom, or maybe there was a temporary bug there or something. But I'm glad to see the issue is resolved for you!

But yeah in that case we can close this out, but if we get more reports of this, or it occurs again, feel free to reopen and we can investigate further into our compile cache process. But tbh there is some ideas about removing many aspects of it, so ideally we won't see this again.

Thanks a ton for taking the time to investigate further!

**Closed by confused-Techie** 2023-06-24 22:08 UTC
Labels: bug
