### ISSUE TITLE
Fix config tests that check for debounces on the `config.set`

### ISSUE THREAD

**Issue by mauricioszabo** [pulsar-edit/pulsar#31] opened 2022-08-24 05:07 UTC
Tests like this are flaky: sometimes they pass, sometimes they dont:

On `spec/config-spec.js`:
```js
    it("saves the user's config to disk after it stops changing", () => {
      atom.config.set('foo.bar.baz', 42);
      expect(savedSettings.length).toBe(0);
      atom.config.set('foo.bar.baz', 43);
      expect(savedSettings.length).toBe(0);
      atom.config.set('foo.bar.baz', 44);
      advanceClock(10);
      expect(savedSettings.length).toBe(1);
    });
```

Changing `advanceClock` to a higher value does nothing either

**Comment by fabianfiorotto** [comment] 2022-08-29 14:44
For some reason, the underscore debounce function is not using the faked date functions but the actual ones. An easy way to get rid of these error messages could be using jasmine's `spyOn` to override debounce with a copy-and-paste version of underscore debounce that uses the faked date functions.
I don't know if it's the cleanest solution but it works. I can crate a PR with it if you want.

**Comment by confused-Techie** [comment] 2022-09-05 09:09
@fabianfiorotto I'm not sure that is the case. I've been looking into this, and for reference, the internal clock, accessed via `advanceClock()` in Pulsar uses the `window.now` API to manage time, meanwhile Underscore's `debounce()` uses their [`now.js`](https://github.com/jashkenas/underscore/blob/master/modules/now.js) which is using `Date.now()`, so initially I thought you were right, that we could mock the `Date.now()` itself, and leave debounce alone, but we already are, in `spec-helper.coffee` we have 

```coffeescript
spyOn(Date, 'now').andCallFake(-> window.now)
```

So it seems that should solve it. At least for the test I've been looking at "saves state when the CPU is idle after a keydown or mousedown event" in `atom-environment-spec.js` the debounce function never returns, even if I change debounce to callback immediately like so 

```javascript
const saveState = _.debounce(() => {
  this.window.requestIdleCallback(() => {
    if (!this.unloading) this.saveState({ isUnloading: false });
  });
}, true);
```

The save state functionality is never called, so its hard to say if this is in fact a debounce issue, we could try updating `underscore-plus` which is one of our repos, that we use for this, and imports the rest of the functions for underscore, or it may be an issue with saveState() handling. But just wanted to add my two cents I've found related to this discussion. 
```

**Comment by confused-Techie** [comment] 2022-09-05 10:06
Additionally while these tests have still left me scratching my head, just wanted to add. In many state management functions of the Pulsar environment, they end up using `atom-environment.js`'s `attachSaveStateListeners()`.

Now I'm not sure what change has prompted this, but there seems to a bug in how it is currently written. Take this excerpt for example:

```javascript
attachSaveStateListeners() {
  const saveState = _.debounce(() => {
    this.window.requestIdleCallback(() => {
      if (!this.unloading) this.saveState({ isUnloading: false });
    });
  }, this.saveStateDebounceInterval);

  this.document.addEventListener('keydown', saveState, { capture: true });
}
```

This is how the code currently works, but after scratching my head on why `debounce` isn't calling the callback properly I set up this small snippet with the only other change in the `addEventListener` calling this new function, rather than `saveState`

```javascript
const testKeydown = function() {
  console.log(`Do we know saveStateDebounceInterval: ${this.saveStateDebounceInterval}`);
  console.log(`Do we know saveState: ${typeof this.saveState}`);
}
```

And surprisingly the results I got back for both:

```shell
Do we know saveStateDebounceInterval: undefined
Do we know saveState: undefined
```

So during assigning the constant as the callback function, it loses its context. Which its strange this was never caught before and must be some sort of change in Node, or something. But regardless, knowing that it doesn't know it's context once its being callback, then when debounce attempts to check when it should fire again, its delta is `undefined` so it never does.

So by adding:

```javascript
this.document.addEventListener('keydown', testKeydown.bind(this), { capture: true });
```

We now get the following from our `testKeydown` function:

```shell
Do we know saveStateDebounceInterval: 1000
Do we know saveState: function
```

While this hasn't lead me to fully resolving the issues present on the test I'm looking at, hopefully it can help you along with finding your own.

**Comment by confused-Techie** [comment] 2022-09-05 19:24
@fabianfiorotto Well fair enough, didn't mean I didn't believe you, just thought there was something else to it. But then in that case I wonder why underscore isn't using our mocked `Date.now()`, thats just so bizarre.

**Comment by fabianfiorotto** [comment] 2022-09-05 19:37
@confused-Techie I don't fully understand how jasmine's `spyOn` works. But this is probably caused by underscore storing the actual date function in a local variable `now` before jasmine does its magic and doesn't have a way to override that local variable.

**Comment by confused-Techie** [comment] 2022-09-05 20:15
@fabianfiorotto So it seems on the older version of `underscore` is slightly different than what I saw on the new version, the new one just returns `Date.now()` but this older one instead uses 

```javascript
var now = Date.now || function() {
  return new Date().getTime();
};

module.exports = now;
```

So that might be whats changed that these tests relied on.

On Line 798 of `node_modules/underscore/underscore-node-f.cjs` I changed 

```javascript
var now = Date.now || function() {
  return new Date().getTime();
};
```

With just 

```javascript
var now = function() {
  return Date.now();
}
```
And like you saw all the tests pass. So we can still let it use its now function, and we could either mock this function, as that'd be much shorter or simpler, or even just update the version of `underscore` we use in `underscore-plus` and hopefully that'd be all it takes.

But as I looked around to do exactly that, I can't seem to actually identify where we are initially importing `underscore-plus`, it's not an included package, and I don't see it in the editors `package.json` I just see it in many of the packages `package.json`. But I didn't think those dependencies were being downloading, since that should give them a local `node_modules` folder right?

**Comment by fabianfiorotto** [comment] 2022-09-05 20:54
I still think that overriding debounce with a copy-and-pasted version is the best solution for now. We can add a comment that says we need a better solution but we need all tests to pass to move forward.

**Comment by confused-Techie** [comment] 2022-09-05 21:01
> I still think that overriding debounce with a copy-and-pasted version is the best solution for now. We can add a comment that says we need a better solution but we need all tests to pass to move forward.

Valid point, It'll be hard to get underscore-plus updated, if its hard to tell if we are breaking new things or not. Fair enough, and we should probably go ahead and create a spy for debounce, and like you said just use `Date.now()` directly. Now I'm not super familiar with CoffeeScript but it would probably make sense to add this to `spec-helper.coffee` so that way its accessible to all of our tests, since we have multiple failing because of this. If you're familiar with coffee you can put it there, or otherwise I'll ping the Discord server and see about merging my PR for decaffeination of that file

**Comment by mauricioszabo** [comment] 2022-09-05 22:01
I'm thinking we could migrate these tests to not use mocks at all. I'll try to draft something, using the Playwright structure so we can compare things...

**Closed** 2022-09-13 00:11 UTC
Labels: failing-test
