### ISSUE TITLE
freezing when editing bash scripts

### ISSUE THREAD

**Issue by jurassicjordan** [pulsar-edit/pulsar#365] opened 2023-02-01 19:46 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

pulsar locks up every 20 or so seconds when editing bash script. I've seen this issue since atom, and it still keeps happening.
It may be related, but it seems to only happen after I wake my computer from suspension (not while pulsar is open)

### Pulsar version

Pulsar  : 1.101.0-beta

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

EndeavourOS Linux, KDE Plasma 5.26.4

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

start writing a bash script
wait
app will eventually lock up for about a minute
sometimes DE will say the app should be force quit

**Comment by confused-Techie** [comment] 2023-02-02 02:53
I appreciate you logging this issue!

To better try and see what's going on, would you be able to grab any logs from when this happens for us to investigate?

**Comment by Daeraxa** [comment] 2023-02-02 03:18
To add to this could you provide an example of text that causes it? Does it happen when you change the language from plain text to bash? Or are you setting it to bash manually first? Or are you starting in an empty `.sh` file or something?

**Comment by jurassicjordan** [comment] 2023-02-02 03:23
> 

I've been doing some testing, opening and creating various files, I've now realized its not just .sh files, it happens with python as well. I've also noticed it only starts lagging and freezing when ive pulled up my script folder (essentially just a folder I put all my .sh and some python files)

**Comment by NZLostboy** [comment] 2023-02-15 03:17
I am having a similar issue, but its not related to a particular file. I am coming from the last released version of Atom (I had no issues there) but with `Intel.Mac.Pulsar-1.101.0-beta.dmg` I get random freezing occurring.

Running MacOS 13.2.1 but I had the issue on the previous version as well.

When it freezes, the `Pulsar Helper (Renderer)` process kicks up, and then when it drops again it unfreezes.

Happy to diagnose further if someone can tell me what logs would help.

**Comment by NZLostboy** [comment] 2023-02-21 01:02
I have been testing version `Intel.Mac.Pulsar-1.102` and I am no longer hitting this issue. Might be worth trying the update @jurassicjordan

**Comment by confused-Techie** [comment] 2023-04-21 00:20
If any languages are causing freezing I'd really recommend trying Pulsar v1.104.0 as that has fixed freezing in some cases.

Otherwise please provide a reproducible example, otherwise we can't test. Even if multiple files cause it, we still need something to work with.

But let me know if the newest version fixes these issues for you

**Comment by confused-Techie** [comment] 2023-05-01 03:52
@jurassicjordan Have you had a chance to test this on the most recent Pulsar version? 

Since without a reproducible snippet of code there's no way for us to confirm this behavior, and otherwise may just have to assume this most recent regular release resolves the issue.

**Comment by NZLostboy** [comment] 2023-05-01 03:55
> @jurassicjordan Have you had a chance to test this on the most recent Pulsar version?
> 
> Since without a reproducible snippet of code there's no way for us to confirm this behavior, and otherwise may just have to assume this most recent regular release resolves the issue.

As a note, I have been using Pulsar 6+ hours a day and have not had the report issue come back.

**Comment by confused-Techie** [comment] 2023-05-01 03:58
@NZLostboy That's fantastic! 

Since I know you were also affected by this original issue and it was fixed for you prior to the huge changes of `1.104.0` I think I'll be happy to consider this one resolved. Appreciate you getting back to me!

But with your confirmation of everything going well I'll go ahead and close it.

@jurassicjordan Feel free to reopen this if the issue continues for you, but fingers crossed everything looks good!

**Closed by confused-Techie** 2023-05-01 03:58 UTC
Labels: bug
