### ISSUE TITLE
Adding pulsar edit as an "external editor" option in github desktop

### ISSUE THREAD

**Issue by dsjosh** [pulsar-edit/pulsar#565] opened 2023-05-29 20:38 UTC
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Hi,

This is more of an extenal integration request than a feature of pulsar itself. Back when atom was part of github, there was (and there still is) atom's integration with github desktop app (as seen in the screenshot attached). However, since those filepaths point to atom and not pulsar, that integration is not transferrable to pulsar.

https://github.com/desktop/desktop/issues/16805

I have raised a feature request with them to add pulsar support (which makes sense because they already have Atom support). But, they seem to not have the capacity to help with this request. And I'm not familiar with their source code language since I am a python dev. I hope someone here can help to integrate pulsar into github desktop.

![Screenshot](https://github.com/pulsar-edit/pulsar/assets/43461340/d3bef59d-db38-4c57-bff6-fb203b389814)

Also, it seems someone already added a macos integration. but windows integration is still pending.

### What benefits does this feature provide?

github desktop has a very large user base of commercial and individual users. I'm sure the users including myself would appreciate.

### Any alternatives?

nil

### Other examples:

The reason I asked the editor team is because I did see the trend of the editor teams adding their own editors into the supported list. The most recent being [this example](https://github.com/desktop/desktop/pull/16338). So, since editors are adding their own integration support, I hope pulsar can do too.

**Comment by confused-Techie** [comment] 2023-05-29 21:15
This is something we have actually looked at before. I'm personally a huge fan of GitHub Desktop for helping to visually manage all my repos and knowing what branch I'm on easily, so the lack of having Pulsar there definitely is a little frustrating.

The reason we haven't yet made a PR to add support for Pulsar on Windows is because the way GitHub Desktop finds applications on Windows is via the GUID of the application within the system registry. But because the original conversation started at a time we were also investigating getting signing on Windows setup, we had a feeling the GUID would be changing, which it would also change if we started using Squirrel to create auto updates for Pulsar. So if we made a PR with the current GUID then it was changed later on we would have to make another and we wanted to avoid that. 

But because at this time we have largely decided against signing on Windows, and there hasn't been any progression on getting auto updates working, it may be a good time to finally investigate getting this working, as there's no other big events that may cause the GUID to change.

So very much appreciate you creating an issue for this, and I really appreciate that you've already investigated with their repo to see if it was something that had to happen on their end, so thanks a ton for contributing!

**Comment by confused-Techie** [comment] 2023-05-29 21:20
Sorry, just went reading through our old chat on this topic, and I misremembered slightly. 

The GUID we have is generated from Electron-Builder (Which we use to generate all of our installers) and that itself is based on the `AppID` within our config. During that time we were adding a few changes to this value to match other platforms and update it from what it was previously. But this wouldn't change based on Autoupdates or signing as I originally mentioned, (That was just my terrible memory lol). So now that we are largely done with that process, there should actually be no issue with doing this at this point in time.

**Comment by dsjosh** [comment] 2023-05-29 22:02
Good to know. Thanks :)

I've subscribed to updates here, so if this is implemented, I'll gladly be the first one to test it out!

**Comment by confused-Techie** [comment] 2023-07-26 00:42
An update on this, now that #604 has been merged, I was finally able to make a PR to the GitHub Desktop repo [here](https://github.com/desktop/desktop/pull/17120). So once that's merged, and once GitHub Desktop releases an update, make sure you have Pulsar version 1.107.0 or higher installed, and this integration should now be working

**Comment by Daeraxa** [comment] 2023-08-23 01:02
Now that it is available in GH Desktop I guess we can close this? I know it has "only" been added for Windows and macOS - I wonder if we can do a PR to add to the Linux part of it even though they don't directly offer a Linux package, it seems they do at least accept PRs for it. Or should we leave this open until that is either confirmed or denied?

**Comment by confused-Techie** [comment] 2023-08-23 01:18
@Daeraxa While I'd love to be able to close this one, it would be nice to have Pulsar supported on every platform, even if that doesn't seem to be the priority for most other editors.

So my vote, is we keep this open if anyone is interesting in bringing this functionality to Linux machines.
As I have no way to test, or verify, if any changes will work on Linux, even if I can make a best guess at the correct paths.
So I'd unfortunately be unable to.

So if any community members or team members would like to take this challenge on, then we can keep it open to track their progress.

But if nobody plans to work on that in the near future, I'd be comfortable closing, as it seems somewhat rare for Linux support in GitHub Desktop to be offered, so while we wouldn't be the exception, seems somewhat within the status quo.

**Comment by confused-Techie** [comment] 2023-08-23 01:20
But to @dsjosh, like Daeraxa said, this update is now live!

GitHub Desktop v3.2.8 now has support for Pulsar on Windows! ([Release Notes](https://desktop.github.com/release-notes/))

**Comment by Daeraxa** [comment] 2023-08-23 01:59
I'll probably have a look tomorrow, it seems pretty simple.

**Comment by dsjosh** [comment] 2023-08-23 04:05
![image](https://github.com/pulsar-edit/pulsar/assets/43461340/46e4b35d-7f41-4642-8f49-79c62b6648fc)

@confused-Techie Does anyone have the Pulsar release installation working with the Github Desktop release installation on Windows? Seems like the resolution is not reflected on my side despite updating both Pulsar and Github Desktop. As you can see, I have Github Desktop v3.2.9 and Pulsar v1.107.1. As you can see from my screenshot above, I can only get Android Studio as an editor from the dropdown list (Pulsar is not in the list) ☹

**Comment by confused-Techie** [comment] 2023-08-23 04:06
@dsjosh I currently have it working on my machine.

I can see you have Pulsar installed, but the biggest question is how did you install Pulsar? Did you put it into a custom location? Or go with the default location?

**Comment by dsjosh** [comment] 2023-08-23 04:09
@confused-Techie  I have pulsar installed in `C:\Program Files\Pulsar` (I believe that is the default Windows installation location). Is that where you have it installed too?

**Comment by confused-Techie** [comment] 2023-08-23 04:14
@dsjosh Ahh, so I was worried this would happen.

But in short, that is not the default location for Pulsar to install on Windows. The default installation location of Pulsar on Windows is `C:\Users\<YOUR_USER>\AppData\Local\Programs\pulsar`.

But our installer lets you customize the location Pulsar is installed into, as it was requested as a feature.

The issue stems from the fact, that when you install Pulsar to another location like your `Program Files` or anywhere that's not under your user account, then Pulsar is installed under the Administrator account of Windows. Which means it's installed within the Machine Registry.

From what I could tell, GitHub Desktop only supported finding applications within the User Registry. Which, if using the default installation of Pulsar, will appear just fine. But if you're installed within the Machine Registry then GitHub Desktop doesn't search there for application data.

So you could resolve this by uninstalling Pulsar, then installing again to the default location, or maybe there's some feature request or possible way to have GitHub Desktop search the machine registry as well as the User registry. (Although I think the reason they haven't done this so far, is that means GitHub Desktop would have to be launched Elevated to Administrator)

**Comment by confused-Techie** [comment] 2023-08-23 04:18
Actually, re-reading their documentation now, it seems there are methods to detect installations within the machine install.

Not sure why I was under the assumption this wasn't possible before.

I'll look into adding this feature for Pulsar as well.

**Comment by dsjosh** [comment] 2023-08-23 04:46
![image](https://github.com/pulsar-edit/pulsar/assets/43461340/643dc208-e65b-45a4-976b-56edc808c42e)

@confused-Techie glad it's possible to add the machine-wide feature too. This is especially helpful to promote enterprise adoption of Pulsar because the endpoint engineer would create an OS image/snapshot with machine-wide installations preinstalled for all employee laptops.

I hope this screenshot above has the information you're looking for.

**Comment by confused-Techie** [comment] 2023-08-23 04:48
Thanks a ton @dsjosh this is exactly what I'm looking for!

And I hope that such a use case could exist for Pulsar, suppose time will tell.

But totally agree, we should strive to support every use case we can

**Comment by confused-Techie** [comment] 2023-08-23 14:48
@dsjosh Amazing they got to it so fast, but looks like my second PR is now merged.

An update to GitHub Desktop should be sent out in about 2 weeks, then these changes should be live!

**Comment by confused-Techie** [comment] 2023-09-08 05:22
Alright, the update for GitHub Desktop is now out that contains this change!

Would love if you could test it out @dsjosh!

Otherwise, as it seems support for Linux isn't a priority, I'll go ahead and let that one happen when it happens for whoever wants to add support for it. Otherwise for what we are able to do here, I think we should be good to go. Thanks for all the help to everyone involved, and thanks a ton for contributing @dsjosh!

**Closed by confused-Techie** 2023-09-08 05:22 UTC
Labels: enhancement

**Comment by Daeraxa** [comment] 2023-09-15 16:18
I have a PR in for the Linux addition - https://github.com/desktop/desktop/pull/17397

**Comment by confused-Techie** [comment] 2023-09-15 22:50
@Daeraxa Awesome to see!

**Comment by confused-Techie** [comment] 2023-09-21 00:04
> Aaaand merged :)

Fantastic! Thanks for getting Linux on there, now every platform is supported!
