### ISSUE TITLE
can't update to latest 

### ISSUE THREAD

**Issue by Ranko-Saotome** [pulsar-edit/pulsar#778] opened 2023-10-19 17:36 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.22UFbK)
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.org.chromium.Chromium.22UFbK)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_Linux.xK4X5J/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

### Pulsar version

1.110.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Zorin os 16.3

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

try running  the appimage on zorin os 16.3

### Additional Information:

this is the latest version that works on my  system https://github.com/pulsar-edit/pulsar/releases/tag/v1.108.0

**Comment by Daeraxa** [comment] 2023-10-19 19:52
For those wondering it seems Zorin 16.3 is a new release but uses Ubuntu 20.04 LTS, hence this is a duplicate of:

https://github.com/pulsar-edit/pulsar/issues/733
https://github.com/pulsar-edit/pulsar/issues/747
https://github.com/pulsar-edit/pulsar/issues/773

**Comment by DeeDeeG** [comment] 2023-10-22 22:40
PR https://github.com/pulsar-edit/pulsar/pull/760 has been merged, which should resolve this issue.

We have Rolling releases out that are built on Ubuntu 20.04. I can confirm what @Daeraxa said just above, by finding Zorin's blog post where they state Zorin 16 is based on Ubuntu 20.04 LTS. (https://blog.zorin.com/2021/08/17/2021-08-17-zorin-os-16-is-released/)

So, with https://github.com/pulsar-edit/pulsar/pull/760 merged, the latest Rolling release binaries should be runnable on Ubuntu 20.04 and distros based on it such as Zorin OS 16.x.

---

You can get the Rolling release binaries here (https://github.com/pulsar-edit/pulsar-rolling-releases/releases), and beyond that, the next Regular release should include the fix as well.

NOTE: For Rolling, the builds of each OS/arch aren't fully synchronized, and their version numbers may drift very slightly based on the time CI ran for each respective OS/arch. As such, not every "release" on the page has binaries for every OS/Arch. So, _if there is no `.deb` or `AppImage` for your arch in the latest Rolling release, please do scroll down to the next one that has a `.deb` or `AppImage` for your desired arch and get the binary from that version._

Or you may find it convenient to just grab the binaries from our website here (https://pulsar-edit.dev/download.html#rolling-release), which will automatically fetch the most recent binary for the OS/arch you ask for.

**Comment by DeeDeeG** [comment] 2023-10-25 04:44
Closing this issue as resolved for Zorin OS 16 users.

Please let us know if there is anything else needed for Zorin OS 16, otherwise it may be best to open a different issue if the topic you're addressing has no open issue for it.

Thanks for the report!

**Closed by DeeDeeG** 2023-10-25 04:44 UTC
Labels: bug
