### ISSUE TITLE
Pulsar not working in RockyLinux9

### ISSUE THREAD

**Issue by stefaniecg** [pulsar-edit/pulsar#747] opened 2023-09-30 09:56 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I installed Pulsar in Rocky Linux 9, but no GUI ever comes up. 

`sudo dnf install -y ./pulsar-1.109.2023092802.x86_64.rpm`

Infos about pulsar and OS below.
Please help, thanx

```
$ pulsar -v  
Pulsar  : 1.109.2023092802  
Electron: 12.2.3  
Chrome  : 89.0.4389.128  
Node    : 14.16.0  
```
```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

```

### Pulsar version

1.109.2023092802 

### Which OS does this happen on?

🐧 Red Hat based (Fedora, Alma, RockyLinux, CentOS Stream, etc.)

### OS details

Rocky Linux 9.2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

In Rocky Linux 9.2 install pulsar:

`sudo dnf install -y ./pulsar-1.109.2023092802.x86_64.rpm`

Then try:

`pulsar`

no GUI comes up. 

### Additional Information:

Thank you for the help you ca provide.

**Comment by Daeraxa** [comment] 2023-09-30 13:24
Probably a duplicate of https://github.com/pulsar-edit/pulsar/issues/733. Can you run it from the terminal and check the error is the same about GLIBC?

**Comment by stefaniecg** [comment] 2023-09-30 17:31
No, it is not the same. 
I have runned pulsar in command line and there are no errors, it just does not open the GUI. 
What is the problem?

![picture](https://cvws.icloud-content.com/B/ATjZibjxbjqbRQLLEBxfGYQ6iDdQAUAx8baLAwv6mOvuwoQx5Jkb6o-1/pulsar_terminal.png?o=As9GH_cnJt7fNQwHpNkbinO7UaE56U2NHCKml_VVEpOu&v=1&x=3&a=CAog88SjE3d4F0xQjpnFIGPf1YviNdcXWpjGl4YJVmCKlWsSaxCZ65C5rjEYmcjsuq4xIgEAUgQ6iDdQWgQb6o-1aiVwN4bJPnmx2SGmLmJNG2SqJyTxtbHuOTi_rXrkAwb_1Qd1rHUUciX47nMcdWGagmdeBWYjDmEDK_4ozENvnVSt2iR8cwE5KhlfIBx-&e=1696098624&fl=&r=1eb524e4-09bd-4af3-9b6a-5d1fbfbb1b3c-1&k=HCqIehilpLF1mbRAbu8hDQ&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=R_zoc_NEcMtdW6xIJSV8fT-vzec&cd=i)

**Comment by confused-Techie** [comment] 2023-10-01 01:42
While I'm not sure if this is the same issue as #146 
It might be beneficial to see if running with `--no-sandbox` or `--in-process-gpu` or even a combination of both gets you any results.

Thanks a ton for reporting the issue, hope this helps

**Comment by stefaniecg** [comment] 2023-10-01 05:03
Hi, unfortunately non of those options got a GUI to appear. 
What could be a work around? 

![picture](https://cvws.icloud-content.com/B/AZvN8ZbX5dWXiiiGXM5P2u_Ws1lVAbHZ6Ww1WpqkI4OHnBqxRLK-9ohi/pulsar_try1.png?o=Ajmr48o3wkQOGdQRNrBolenTGQxccM40ApTgj1iH8Wrn&v=1&x=3&a=CAogcJ1rqHjMiuPDsIBdhq2hfMflMKSAx6X7pZfLiO_RfA4SaxC_1fjMrjEYv7LUzq4xIgEAUgTWs1lVWgS-9ohiaiXzfSxpkwgc3BKCocUsZOGwwyEGcZhJrU37NBZ9tjvP0Ze8OaaeciWvzVq8PuTj3jHzNtkYZvOsYLNiMpZp5xywprIIr4X0V8morPI1&e=1696140171&fl=&r=7431e609-62be-4cb6-8d62-e393c3ae60a9-1&k=P6TGCFDcII6E8ISDAhNczQ&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=AF1gpPqmEvA5ehnlVlPWdN3xRc0&cd=i)

**Comment by Charadon** [comment] 2023-10-01 08:02
> I think it's not the same. I have runned pulsar in command line and there are no errors, it just does not open the GUI. What is the problem? How can i have a work around it? Should i install a previous versoin of Pulsar or another binary? Please let me know, thank u
> 
> ![picture](https://camo.githubusercontent.com/a761a74d7f300f410cd72ad8a9ad0bb6597fca432f7d23e1b7ccf77cd8f36f47/68747470733a2f2f637677732e69636c6f75642d636f6e74656e742e636f6d2f422f4162744d524d42783365794957326679655544774d62686543344c4e41556e33623665546a4d6f4757463553647a6b333171384e7a6e61712f70756c7361725f7465726d696e616c2e706e673f6f3d416c333979524c4633424937724a742d51383674575756396364774e49345f495543533774797566556c537326763d3126783d3326613d43416f675343684a6e757968427357594b7977473342534b2d38326a3673727236314a6559716e38542d7143653859536178435f734a6935726a45597634333075713478496745415567526543344c4e5767514e7a6e61716169555667445f7874756b636b504d353742596264447a4f354b65467631453030756d2d41545741537971306c794e797458507463695639306f65585a743744416f547150484b77487a58575449304870327777776762464e49384a6a613559374a71313734414826653d3136393630393837343826666c3d26723d62383863613636612d376134322d343833372d396661312d3532613035303762643231392d31266b3d596749577162566b5176796343535464325646646d5126636b633d636f6d2e6170706c652e636c6f7564646f637326636b7a3d636f6d2e6170706c652e436c6f7564446f637326703d31303726733d696a574a54304c2d444b7168544133793577584d78444175344c382663643d69)

Are you running pulsar with the `-f` flag when running from the command-line? Otherwise it won't show any output.

**Comment by stefaniecg** [comment] 2023-10-01 12:27
With the `-f`  option now we get some error feedback. 
Is there a work around ?

```
$ pulsar -f
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.org.chromium.Chromium.085Hct)
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.org.chromium.Chromium.085Hct)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Pulsar/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

```

**Comment by stefaniecg** [comment] 2023-10-01 12:52
I have taken a look and the file `/lib64/libstdc++.so.6` does exist. 
So I'm not sure what the problem is. 
Why this version is not accepted by pulsar?

Alternativelly i thought i could copy the "right version" of `libstdc++.so.6` to my local libraries directory: `/usr/local/lib64`, would that help?
In which case: what is the "right version"?

Please let me know what i can do to run Pulsar on this distribution, thank you.

**Comment by DeeDeeG** [comment] 2023-10-01 16:14
> Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.org.chromium.Chromium.085Hct)

I think we should build on the oldest Linux CI will let us. Older Linux in CI will include older glibc.

Newer glibc occasionally has breaking changes that aren't backward-compatible. So, official Atom always stayed building on the oldest Linux the CI environment would let them use, for broadest compatibility with long-lived distros that are very much not "bleeding edge" in their updates, especially (at the time) CentOS, so this being an issue for the Red Hat extended family today is a bit of a callback to that previous discussion I remember from official Atom.

**Comment by stefaniecg** [comment] 2023-10-01 16:46
@DeeDeeG, thank you for yoru answer, yet I don't understanding exacly what I need to do to get **Pulsar** running in my RockyLinux9 distribution. :)

I'm not sure how to _"build on the oldest Linux version that CI will let us build on"_, but if you explain a bit what needs to be done, i can try it out. :)

Or maybe some else could help out with "_building_" these binaries. 

Let me know how to move forward, as I'd love to get **Pulsar** running on my Rocky instalation. 
Thank you for your help.

**Comment by aalbacetef** [comment] 2023-10-01 19:35
> @DeeDeeG, thank you for your answer, yet I don't understanding exacly what I need to do to get **Pulsar** running in my RockyLinux9 distribution. :)
> 
> I'm not sure how to _"build on the oldest Linux version that CI will let us build on"_, but if you explain a bit what needs to be done, i can try it out. :)
> 
> Or maybe someone else could help out with the "_building_" of these binaries.
> 
> Let me know how to move forward, as I'd love to get **Pulsar** running on my Rocky instalation. :) Thank you for your help.

Can you try the appimage instead? It might be better than tinkering with your glibc installation (btw: ldd --version should spit out the version you have).

**Comment by aalbacetef** [comment] 2023-10-01 19:44
@Daeraxa it would be a good idea to downgrade the build process to an older version and also to use the bitnami/minideb images. I'd be happy to give it a try.

**Comment by stefaniecg** [comment] 2023-10-01 20:06
> 
> Can you try the appimage instead? It might be better than tinkering with your glibc installation (btw: ldd --version should spit out the version you have).

Regarding `ldd`, here is the terminal output:
```
$ldd --version
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
```

Regarding trying the **AppImage**, i want to try this.
Meaning i will download the Appimage version of the Rolling release: [Pulsar-1.109.2023100116.AppImage](https://download.pulsar-edit.dev/?os=linux&type=linux_appimage) and install it by double clicking it. Right?

But before i install it, can someone please tell me how to **uninstall** the current Pulsar installation? so i get a clean new appimage install

Thank you for your help !

**Comment by Daeraxa** [comment] 2023-10-01 21:56
@stefaniecg Appimages don't actually install (unless you are using AppimageLauncher which will prompt anyway), they are essentially self contained applications. You can have it alongside an installed version and it would work the same (as they use the same config folder). You should be able to uninstall with `dnf remove pulsar`, Pulsar was installed but you just couldn't launch it.

@aalbacetef I'll have to defer to the experts there I'm afraid, @DeeDeeG for example has a much better handle on this.

**Comment by aalbacetef** [comment] 2023-10-01 22:15
@stefaniecg You can uninstall using the command that @Daeraxa wrote.

As per the AppImage, think of it as a portable binary, you don't install it, you run it (don't forget to `chmod +x` it!). 

Here's what I suggest:
- create a directory where you'd like to place the AppImage (if you don't already have one), some people like using `~/.local/bin`, others `/opt/bin`,  your choice!
- add it to your path: at the end of your `~/.bashrc` add a line `export PATH="/path/to/new/dir:$PATH"`
- (optional) either rename the AppImage to pulsar or symlink it with `ln -s`

Now you should be able to launch pulsar directly from the terminal.

If you'd like to have it run as an app, you'll want to create a .desktop file.

Here's an example of a `pulsar.desktop`:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Terminal=false
Type=Application
Name=Pulsar
Exec=/path/to/bin/pulsar
Categories=Utility;
```

and drop it in the appropriate directory, usually `~/.local/share/applications`.

**Comment by stefaniecg** [comment] 2023-10-02 07:58
So i uninstalled pulsar with: `sudo dnf remove pulsar`, 
then `chmod +x Pulsar-1.109.2023100116.AppImage`, 
then executed it `./Pulsar-1.109.2023100116.AppImage `, but the same error popped up. 
What can i do now? :)
Thank you so much for your help. 

```
$./Pulsar-1.109.2023100116.AppImage 
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.org.chromium.Chromium.XIxwSK)
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.org.chromium.Chromium.XIxwSK)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/.mount_PulsarenEM92/resources/app.asar/node_modules/nsfw/js/src/index.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)

```

**Comment by Daeraxa** [comment] 2023-10-02 08:33
Unfortunately I think the only answer at the moment is to go for an earlier release until we sort out what we are going to do. Essentially we are building Pulsar on a machine that means older versions of Linux aren't supported.

**Comment by stefaniecg** [comment] 2023-10-02 12:22
@Daeraxa, ok, i'll do that. 
What earlier release would work? 
Where do i download it?

Thank you for the help :)

**Comment by Charadon** [comment] 2023-10-02 13:52
> @Daeraxa, ok, i'll do that. What earlier release would work? Where do i download it?
> 
> Thank you for the help :)

I compiled some binaries that were made on Debian 8, you can try these and tell me if they work: https://ftp.iotib.net/Projects/Pulsar%20Older%20Glibc/v1.109.0/

If not, then you could use the flatpak?

**Comment by stefaniecg** [comment] 2023-10-02 16:13
@Charadon, 
I downloaded your binaries and installed `sudo dnf install -y ./pulsar-1.109.0.x86_64.rpm` and it worked like a charm !  
Thank you so much for your help ! 👍

**Comment by Charadon** [comment] 2023-10-02 16:31
> Just a couple of questions, to get an idea:
> 
> Q1. what was the problem? is it that Rocky9 OS has too **OLD** or too **NEW** versions of the `libstdc++.so.6` library? Q2. i understand that these are the only binaries that will work for my distribution now, do you have an idea when will i be able to **use the 'normal'** binaries for installation? i.e. update Pulsar.
> 
> Let me know. Thank you all for your support :)

I wrote up an explanation on why this happens here: https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1728645942

**Comment by DeeDeeG** [comment] 2023-10-17 02:46
Hi again, sorry for the delayed response.

> Q1. what was the problem? is it that Rocky9 OS has too OLD or too NEW versions of the libstdc++.so.6 library?

The problem is Rocky 9 having too _old_ a version of glibc, or in other words the problem is Pulsar being compiled for too _new_ a version of glibc to be compatible.

>  Q2. i understand that these are the only binaries that will work for my distribution now, do you have an idea when will i be able to use the 'normal' binaries for installation? i.e. update Pulsar.

We have some binaries generated by Pulsar team now, if you prefer those. (See: https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1763556992.)

As for a timeline for when these binaries might be made routinely during our release process: We are still running into some problems when trying to automatically test these binaries for quality assurance purposes, to confirm they continue to work with each change to Pulsar during deveopment, but folks have who have tried them manually so far have commented that it's working for them.

If we can't find a way to automatically test these like we test our other binaries, we may provide them "as-is" as separate "legacy" binaries. We're still figuring out what we want to do about this, to be honest.

More details in my comment in the other issue: https://github.com/pulsar-edit/pulsar/issues/733#issuecomment-1763556992

I'm not sure how much work it will take to make progress on automated testing, so no firm plans at the moment regarding when we'd want to make these widely available as part of our usual releases.

**Closed** 2024-01-29 06:17 UTC
Labels: bug

**Comment by stefaniecg** [comment] 2024-01-29 11:56
@confused-Techie , hi, so i can now install Pulsar in RockyLInux9 using the Pulsar Regular Release for linux installer from  the website?

**Comment by confused-Techie** [comment] 2024-01-29 16:02
> @confused-Techie , hi, so i can now install Pulsar in RockyLInux9 using the Pulsar Regular Release for linux installer from the website?

If the PR has worked as intended then on the next Pulsar Regular Release yes you could. So keep an eye out for our Pulsar Release in mid February, or otherwise if you install the Rolling Release, that should already have this fix.

**Comment by stefaniecg** [comment] 2024-01-29 16:19
ok @confused-Techie , thank you so much for your help !
