### ISSUE TITLE
Pulsar innerHTML renders 9 as dash in pulsar panel.

### ISSUE THREAD

**Issue by ianwillie** [pulsar-edit/pulsar#475] opened 2023-04-07 18:10 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When rendering a string of number "1234567890" with innerHTML to addBottomPanel the result in Pulsar 1.103 is "12345678--0".  In the output what I have shown as -- is actually a long dash which I don't know how to show here: this is seen on the screenshot. In Atom 1.60 the result is as expected "1234567890".  The same behaviour shows in modal & other panels.
I first noticed this is writing a package to emulate the asciidoc-preview which does not work in Pulsar or Atom versions 1.61 onwards. [https://github.com/pulsar-edit/pulsar/issues/256](https://github.com/pulsar-edit/pulsar/issues/256)

The behaviour is shown in the screenshots attached: The pulsar with the error:
![innerHTMLRenderingError_PulsarV1-103_DashInPlaceOf9_Screenshot_2023-04-07_17-46-49](https://user-images.githubusercontent.com/37041622/230651675-cc09386c-6fb4-4a3a-a6ce-4b3b90355d1a.png)

Atom with the proper rendering:
![innerHTMLRenderingError_AtomV1-60_OK_Screenshot_2023-04-07_17-46-49](https://user-images.githubusercontent.com/37041622/230651702-303b6603-66ab-4b0d-81d4-e9a8bc16bbf3.png)

This was achieved by creating a init.js file which contained:

```js
atom.commands.add("atom-text-editor", "send-string-to-innerHTML", () => {
  const child_process = require('child_process');
  const fs = require("fs");
  let htmlstring;
  const div = document.createElement( 'div');
  div.innerHTML = '<h2> Hello </h2> 1234567890';
atom.workspace.addBottomPanel({item: div});
});
```

Hopefully you can see in the screenshots 1. the end of init.js, the version of atom/pulsar being used, and at the bottom the output from innerHTML. This is the simplest way that I could prepare an abstraction that would not have the complexity of the package that I am making.  Console output is below.
[Pulsar1_103_innerHTML_9RenderedAsDash_Console.txt](https://github.com/pulsar-edit/pulsar/files/11180599/Pulsar1_103_innerHTML_9RenderedAsDash_Console.txt)

EDIT: I forgot to include other characters but all uppercase & lowercase letters render correctly. I did not test other non printing and punctuation characters.

### Pulsar version

1.103.2023040323 x64 and earlier ones too.

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Manjaro latest update 20230407

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Edit pulsar init.js to contain below and save the file. Use the file input because the &lt;h2&gt; Hello renders on this page and should be text surrounded by `h2` tags.

  ```js
  atom.commands.add("atom-text-editor", "send-string-to-innerHTML", () => {
    const child_process = require('child_process');
    const fs = require("fs");
    let htmlstring;
    const div = document.createElement( 'div');
    div.innerHTML = '<h2> Hello </h2> 1234567890';
    atom.workspace.addBottomPanel({item: div});
  });
  ```

  [Pulsar1_103_innerHTML_9RenderedAsDash_init.js.txt](https://github.com/pulsar-edit/pulsar/files/11180585/Pulsar1_103_innerHTML_9RenderedAsDash_init.js.txt)

2. Restart pulsar with Ctrl-Shift-F5. This will re-read init.js and install the "send string to innerHTML" command.
3. Press Ctrl-shift-P and the select the "send string to innerHTML"  command from the list by staring to type send- and so on.
4. Look at bottom panel to see output. Hopefully you will see the correct output and you will be able to tell why I am getting the dash in place of 9 or,
5. Wonder why you are seeing the strange dash in place of the 9 and then enlighten me as to what is happening.

**Comment by Meadowsys** [comment] 2023-04-07 18:30
hm... I'm not able to reproduce on macOS (Apple Silicon) Pulsar v1.103.2023040716

**Comment by savetheclocktower** [comment] 2023-04-07 20:18
Can't reproduce this either.

@ianwillie, try opening the developer console (View -> Developer -> Toggle Developer Tools, then focus the “Console” tab) and pasting in just this part:

```js
const div = document.createElement( 'div');
div.innerHTML = '<h2>Hello</h2> 1234567890';
atom.workspace.addBottomPanel({item: div});
```

After you press <kbd>Enter</kbd>, the panel should appear at the bottom. You can then change the `innerHTML` with further console commands and see the results in real time, like so:

```js
div.innerHTML = "9";
```

Play around with different contents and see if there are any situations where the `9` renders as an actual `9`. When you get the dash instead of the `9`, try also just executing

```js
div.innerHTML;
```

so that you can discover what Pulsar thinks the contents of that `div` actually are.

**Comment by ianwillie** [comment] 2023-04-07 21:31
@savetheclocktower  Thanks for your prompt help everyone & showing me how to use the console.  I am a bit of a beginner with node, js & pulsar packages.
You will see from the attached that 9999999999 yields lost of dashes & div.innerHTML on its own shows all 9s no dashes.
Everything else yields just what is expected.
How would I enter the long dash to see what that does because I cannot copy it for pasting from the bottom panel?
![innerHTMLRenderingError_9999999liedsDashes_Screenshot_2023-04-07_17-46-49](https://user-images.githubusercontent.com/37041622/230681366-7029eb27-99ae-4d28-bf46-8c9e7376d1b6.png)

**Comment by confused-Techie** [comment] 2023-04-07 21:48
@ianwillie You could try (with your current setup)

```javascript
console.log(div.innerText | div.textContent);
```

That should print out to the CLI in DevTools what it thinks the text content is. That would tell us if it's been converted to `-` or if it's still a `9` internally.

Also quick question, does this happen if you change your UI Theme, and Syntax Theme?

**Comment by Meadowsys** [comment] 2023-04-07 21:48
> How would I enter the long dash

is it possible to inspect element on the bottom panel and copy it out of there?

**Comment by ianwillie** [comment] 2023-04-07 22:16
@savetheclocktower  Thanks for your prompt help everyone & showing me how to use the console.  I am a bit of a beginner with node, js & pulsar packages.
You will see from the attached that 9999999999 yields lost of dashes & div.innerHTML on its own shows all 9s no dashes.
Everything else yields just what is expected.
How would I enter the long dash to see what that does because I cannot copy it for pasting from the bottom panel?
![innerHTMLRenderingError_9999999liedsDashes_Screenshot_2023-04-07_17-46-49](https://user-images.githubusercontent.com/37041622/230681366-7029eb27-99ae-4d28-bf46-8c9e7376d1b6.png)

**Comment by ianwillie** [comment] 2023-04-07 22:19
@confused-Techie  Brilliant - you have solved it. I was using Atom Dark UI. When I changed to Atom Light the problem vanished. Then when it was changed back to Atom Dark again it was still OK.
I will check it out a bit more but you seem to have fixed it for me. Thank you.

**Comment by confused-Techie** [comment] 2023-04-07 22:33
That's fantastic to hear! Very interesting it happened at all. But knowing that I'll continue to see if I can replicate that, since I'm not seeing anywhere in the source that I'd think would cause this. Then just to confirm this was the preinstalled `Atom Dark` UI Theme? It wasn't one that you installed separately? 

But now to answer your edit, tbh I'm not sure. The only thing I can think of is it bugged when converting the theme from `less` somehow? Since I think there's a cache for themes once transpiled, and it's possible that was just broken, and changing from then back got it to re-transpile, really hard to say tbh

**Comment by savetheclocktower** [comment] 2023-04-07 22:52
Just a wild guess, but it really feels like some sort of bizarre text-rendering bug in old Chromium. I don't imagine @ianwillie will be able to reproduce it again, but if so, I'd bet money on it going way the next time we upgrade Electron.

**Comment by ianwillie** [comment] 2023-04-08 15:08
> That's fantastic to hear! Very interesting it happened at all. But knowing that I'll continue to see if I can replicate that, since I'm not seeing anywhere in the source that I'd think would cause this. Then just to confirm this was the preinstalled `Atom Dark` UI Theme? It wasn't one that you installed separately?
@confused-Techie It was the Atom Dark UI Theme just as it came preinstalled.  Also all working correctly now.

**Comment by Spiker985** [comment] 2023-04-20 08:11
We'll close this for now, since the issues appears to be rendering related and is easily fixed via toggling the UI theme.

If this reoccurs, please open another Issue and reference this one.

**Closed by Spiker985** 2023-04-20 08:11 UTC
Labels: bug
