### ISSUE TITLE
C syntax highlighting broken in 1.113

### ISSUE THREAD

**Issue by Tamaranch** [pulsar-edit/pulsar#872] opened 2024-01-18 12:52 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

After upgrading from 1.112 to 1.113, C syntax highlighting is broken: types are not highlighted, some identifiers are highlighted, others are not, some function names are highlighted in a color, others in another color… see screenshots below:

1.112:
![pulsar-1 112](https://github.com/pulsar-edit/pulsar/assets/41806113/1ac5fe7a-2240-4b49-bb91-b5551eae418f)

1.113:
![pulsar-1 113](https://github.com/pulsar-edit/pulsar/assets/41806113/55c2588b-0303-4e24-a73a-948496189292)

`--safe` fixes things a bit, but not entirely (I'm using One Dark/Spacegray Chalk above):

1.112-safe:
![pulsar-1 112-safe](https://github.com/pulsar-edit/pulsar/assets/41806113/8d29e2de-724b-4afb-9bc4-34b34d5f4bb0)

1.113-safe:
![pulsar-1 113-safe](https://github.com/pulsar-edit/pulsar/assets/41806113/fc08a6d8-703b-4fb9-8c55-09192b359dab)

Here is the file used to test in the screenshots: https://gitlab.xfce.org/xfce/tumbler/-/blob/230e62f9bea2895509d4099a59806fa10c912ca7/plugins/xdg-cache/xdg-cache-thumbnail.c#L69

### Pulsar version

1.113

### Which OS does this happen on?

🐧 Arch based (Manjaro, Garuda, etc.)

### OS details

Arch Linux

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

* Upgrade from 1.112 to 1.113
* Open C source file, e.g. https://gitlab.xfce.org/xfce/tumbler/-/blob/230e62f9bea2895509d4099a59806fa10c912ca7/plugins/xdg-cache/xdg-cache-thumbnail.c

**Comment by jakubhruby** [comment] 2024-01-18 13:50
Same for me on TypeScript, the whole thing looks like not highlighted at all:
![image](https://github.com/pulsar-edit/pulsar/assets/8798755/e1132439-00c4-4068-aa52-def73e05c490)

**Comment by croaker000** [comment] 2024-01-18 14:18
Same for me on mixed HTML & PHP.
Start Pulsar, open a file - all works fine. After a period of time, something snaps and the text highlighting stops working for the HTML portions.
Also, once broken, snippets also stop working and CTRL-/ comment toggling miscalculates the type of toggling required (ie. for PHP syntax, it tries to implement HTML comments)

**Comment by confused-Techie** [comment] 2024-01-18 15:25
Thanks a ton for all the issue reports here!

This very likely is due to the fact we have enabled Modern TreeSitter by default, and disabled Legacy TreeSitter.

You can always revert this change via Settings "editor.useLegacyTreeSitter", so feel free to do so if this is mission critical. Otherwise I'd like yo implore you not to disable Modern TreeSitter. This is because sometime soon we will have to remove Legacy TreeSitter completely, so it's much better to make it perfect now, rather than deal with these issues when there is no way to go back.

@savetheclocktower If you could take a look, otherwise maybe we want to create one larger issue for syntax highlighting differences in 1.113.0 but hard to say.

**Comment by Tamaranch** [comment] 2024-01-18 16:17
> This very likely is due to the fact we have enabled Modern TreeSitter by default, and disabled Legacy TreeSitter.

I can confirm disabling Modern TreeSitter implementation solves the issue for C language.

**Comment by croaker000** [comment] 2024-01-18 16:20
Yep, disabling Modern TreeSitter fixes my PHP/HTML issues. Happy to switch it back on for testing and help fix but I need to be able to actually work so will keep it disabled for now.

**Comment by savetheclocktower** [comment] 2024-01-18 21:28
@Tamaranch, @croaker000  Ideally, it's best to disable it on a grammar-by-grammar basis:

```coffeescript
".c.source":
  core:
    useLegacyTreeSitter: true
```

or 

```coffeescript
".text.html.php":
  core:
    useLegacyTreeSitter: true
```

so that it's not disabled across the board.

Let's keep this as the C-related issue for syntax highlighting changes and then add others on a grammar-by-grammar basis as needed.

**Comment by croaker000** [comment] 2024-01-18 21:36
Do we have any grammars that are actually confirmed as working? I can test HTML, PHP and Javascript for you (and combinations of mixed content) but I'm pretty sure they'll break in the same way from my experiences with them so far this week.
It's tricky because, for me, all is fine to start with and only stops working after some unspecified length of time.
I won't be using any other grammars for my project for the foreseeable unfortunately.
If you need me to try anything, let me know.

**Comment by savetheclocktower** [comment] 2024-01-18 21:42
@croaker000, I don't spend most of my day in PHP, but I haven't encountered issues like the ones you're describing.

I have a hunch about what may be happening, though. So I'd ask that you keep the modern PHP grammar enabled just until this happens again — then open the developer tools, go to the Console tab, and see if anything looks like it exploded. Specifically, look for a yellow/orange message that starts with `Warning: parser wants to call function` (you can filter the messages at the top of the list), or anything that's red.

My hunch is that some parsers have some code paths that use builtin C functions that are not bundled in the standard version of `web-tree-sitter`, and that these code paths are very rare and only arise in unusual situations. (Obviously, a reduced test case would be solid gold, though I know it's unlikely to happen in most cases.)

**Comment by croaker000** [comment] 2024-01-18 21:57
I did look there a few times before this bug got reported and I jumped on it - with nothing popping up. I'll do that in the morning (UK time - GMT) and see what happens this time. I do have a few plugins running, is it worth disabling them to run the tests?

**Comment by Tamaranch** [comment] 2024-01-18 23:42
Having done some testing in other languages, I'm wondering if some of the things above aren't as expected, such as the difference in highlighting of function names when they're defined or used. More generally, I imagine that not everything is supposed to be the same between Legacy and Modern TreeSitter? (i.e. it's not just a question of performance)

Despite this doubt, I think there are broken things also in C++ (somewhat similarly to C above), in python (e.g. the `None` keyword which is not highlighted), and in shell (e.g. the `while` keyword which is not highlighted).

**Comment by savetheclocktower** [comment] 2024-01-18 23:49
> More generally, I imagine that not everything is supposed to be the same between Legacy and Modern TreeSitter? (i.e. it's not just a question of performance)

Correct. I need to write some sort of authoritative document, but in short this will take the form of a triage process:

* Genuine regressions (which I'm sure there are a lot of)
* Unintended side effects of intentional changes in scope names (which usually should not result in vastly different highlighting; this is still on us to fix, but the “fix” might come in the built-in syntax themes)
* Differences of opinion (in which case the tools are there for you to apply overrides in your user stylesheet, and we'll even tell you how to do it)

For instance, it was a _purposeful_ goal to separate scope names for function definition and usage _without_ affecting any of the built-in syntax themes. If you've found places where that isn't the case, that'd qualify as a bug in my mind.

> Despite this doubt, I think there are broken things also in C++ (somewhat similarly to C above), in python (e.g. the None keyword which is not highlighted), and in shell (e.g. the while keyword which is not highlighted).

C/C++ share a package and share most of their highlighting decisions, so that makes sense. And `None` is properly highlighted for me, so I'm curious where you're seeing that. But _damn!_ How did I miss `while` in the shell?

OK, in a few hours I'll be creating issues for each of the built-in grammars just so we can keep track of these.

**Comment by confused-Techie** [comment] 2024-01-19 00:49
@savetheclocktower Do we want to create a mega issue for C as well, so that you can get your recommendations on fixing behavior temporarily up at the top, and we close this one?

**Comment by Tamaranch** [comment] 2024-01-19 01:05
> And `None` is properly highlighted for me, so I'm curious where you're seeing that.

This seems to be quite specific to the Spacegray Chalk syntax theme (spacegray-chalk-syntax package). It's old and makes deprecated calls apparently, I may try using another theme.

**Comment by savetheclocktower** [comment] 2024-01-19 01:12
> > And `None` is properly highlighted for me, so I'm curious where you're seeing that.
> 
> This seems to be quite specific to the Spacegray Chalk syntax theme (spacegray-chalk-syntax package). It's old and makes deprecated calls apparently, I may try using another theme.

I bet I know what happened: the old scope name in TextMate is `constant.language.python` and the new scope name is `constant.builtil.none.python`. It wouldn't surprise me too much if a theme explicitly assigned the `.none` class name to mean “plain text,” especially if they meant to use it only internally as a LESS mixin. If the same thing isn't happening to `True` or `False`, that's probably the culprit.

In any case, you can override it in your user stylesheet:

```less
.syntax--source.syntax--python {
  .syntax--none { color: #123456; } // or whatever color constants are supposed to be in that theme
}
```

**Comment by savetheclocktower** [comment] 2024-01-19 01:15
Yeah, [that's exactly what's going on](https://github.com/vyder/spacegray-chalk/blob/master/styles/base.less#L259-L261). It's even a legacy theme without the `syntax--` prefixes! Still, with that tiny override, you should still be good to go.

**Comment by Tamaranch** [comment] 2024-01-19 01:24
Yes it works, thanks!

**Comment by savetheclocktower** [comment] 2024-01-19 02:44
@Tamaranch, “make this file look similar to how it did in the older grammar” is a very easy task, so thank you for the reference file you provided me. The changes I made [are described here](https://github.com/pulsar-edit/pulsar/issues/877#issuecomment-1899552104).

With that, I think I'll close this issue in favor of the mega-issues I've since created. Thanks again for the report, and please drop a comment into #877 if you notice other highlighting disparities in C/C++ that are not yet addressed.

**Comment by savetheclocktower** [comment] 2024-01-19 02:46
Likewise, @croaker000, we can continue the PHP discussion in #876; @jakubhruby, you can follow me to #874 for TypeScript issues.

**Closed** 2024-01-19 02:46 UTC
Labels: bug
