### ISSUE TITLE
Adding Pulsar to PATH failure with space in the path

### ISSUE THREAD

**Issue by 2colours** [pulsar-edit/pulsar#816] opened 2023-11-25 13:04 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

Adding Pulsar to PATH using the checkbox in the settings can fail with a folder name that contains a space. This is especially problematic because on Windows, the default system-wide installation path itself contains a space.
![image](https://github.com/pulsar-edit/pulsar/assets/37218286/1c1b7794-63d9-498f-9e2c-2146713e00ea)

### Pulsar version

1.111.0

### Which OS does this happen on?

🪟 Windows

### OS details

Windows 10.0.19045 build 19045

### Which CPU architecture are you running this on?

x86_64/AMD64

### What steps are needed to reproduce this?

1. install Pulsar globally, to a place that contains spaces in its name (the default "Program Files" path will probably do; I'm using "New programs" on the secondary drive)
2. Run Pulsar as administrator
3. Open File / Settings
4. Go to the System page
5. Click "Add Pulsar to PATH"

**Comment by confused-Techie** [comment] 2023-12-02 07:09
Thanks a ton for reporting this issue!

Taking a look, this issue is almost absolutely caused by the following line:

https://github.com/pulsar-edit/pulsar/blob/c16743e2c43a885c199077547635e59a56a8d7f5/src/main-process/win-shell.js#L132

Which could likely be fixed by instead using:

```javascript
const child = ChildProcess.execFile(
          `"${pulsarPath}\\resources\\modifyWindowsPath.ps1"`,
          ['-installMode', this.installMode, '-installdir', `"${pulsarPath}"`, '-remove', '0'],
          { shell: "powershell.exe" },
```

Instead. I'm out on vacation now, so unable to take the time to make the PR, but if anyone else has the availability, I'm rather confident this would resolve this issue, otherwise I'll get to it as soon as I can.

**Closed** 2024-04-06 19:41 UTC
Labels: bug
