### ISSUE TITLE
Incorrect syntax marking for Bash / Bourne shell script, `if ... >x -x "x" "x" ...` 

### ISSUE THREAD

**Issue by danfuzz** [pulsar-edit/pulsar#736] opened 2023-09-22 21:02 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I noticed that the `shellscript` syntax highlighter was behaving oddly on some of my code, and I managed to distill it down to a pretty short example that still exhibits the same behavior. I _think_ the crux of the problem is in the handling of FD redirects (`>whatever`) that appear somewhere other than at the end of the line.

```bash
#!/bin/bash

if true; then
    : >x -x "x" "x"
fi || {
    : "x"
}
```

This is how I see it rendered:

<img width="195" alt="wacky" src="https://github.com/pulsar-edit/pulsar/assets/1090235/dfca0aa4-c541-4530-b8b7-ac01d54b015b">

### Pulsar version

1.109.0

### Which OS does this happen on?

🍎 macOS

### OS details

13.5.2

### Which CPU architecture are you running this on?

Apple M1/M2

### What steps are needed to reproduce this?

1. Make a file called `whatever.sh`
2. Paste the text above.
3. Observe the incorrect syntax highlighting.

**Comment by savetheclocktower** [comment] 2023-09-22 21:11
Modern tree-sitter appears to have fixed this. Make sure “Use Modern Tree-Sitter Implementation” is checked in your settings.

**Comment by danfuzz** [comment] 2023-09-22 21:25
@savetheclocktower Thanks for the quick reply. Indeed it looks like that specific example is fixed, but I quickly found another case of what looks like the same problem (but a bit more involved to trigger):

```bash
#!/bin/bash

if true; then
    : >x -x "x" "x"
fi

if true; then
    : >x -x "x" "x"
fi || {
    : "x"
}
```

Rendered as:

<img width="205" alt="wacky-2" src="https://github.com/pulsar-edit/pulsar/assets/1090235/ac7bab84-21c0-4add-81e0-f5ef1e9b3645">

**Comment by danfuzz** [comment] 2023-09-22 21:34
BTW, per the suggestion "Contributions are greatly appreciated" in the README of `language-shellscript`:

I tried looking at the source, and ran into <https://github.com/pulsar-edit/pulsar/blob/master/packages/language-shellscript/grammars/tree-sitter/tree-sitter-bash.wasm>, which looks like a prebuilt binary directly checked into the tree. It's unclear where it comes from. I _did_ find the separate package <https://github.com/tree-sitter/tree-sitter-bash>, but I was unable to figure out if the `.wasm` file is a blob made from that repo and if so how and what version.

**Comment by savetheclocktower** [comment] 2023-09-22 23:20
That's fair. I need to do a better job of noting that information when I generate the WASM files — especially since I don't even remember myself which version of `tree-sitter-bash` I generated it from.

I checked out the latest from that repo and confirmed that your second example is fixed and seems to parse correctly. I built a new WASM file and verified myself that the syntax highlighting is correct now. I'll add it to #735.

I'll also make a note in the grammar's CSON file to point to the Git commit from which the WASM file was generated. That's a good habit to develop.

Thanks a lot for the report. This fix will go out in about three weeks.

**Comment by confused-Techie** [comment] 2023-09-22 23:29
Overall glad we found a solution here, but @savetheclocktower I really like the idea of linking a commit for the WASM files, is there an appropriate key to store this in already? Could be super useful to display in the settings UI of the package so that we can always check it if needed maybe?

**Comment by savetheclocktower** [comment] 2023-09-22 23:32
Right now I'm just putting it in as a comment in the CSON file. I'm open to something more formalized.

The key is figuring out how to assert that it's true. There could be a mismatch between the version we claimed to use and the version we actually used, as would happen if someone bumped the WASM file but forgot to add the right metadata somewhere else. That would have to be solved with process somehow — enforcing that the metadata changes at least as often as the WASM file changes.

**Comment by confused-Techie** [comment] 2023-09-22 23:44
@savetheclocktower Yeah while comments are good, I would love to have it properly formalized.

From your perspective, do you think it's enough to confirm that if the WASM file has changed, and the commit used has changed then everything's good? Or would we want to confirm that the commit being used is able to generate the WASM file exactly?

Since we could easily build a GitHub Action that confirms both files have changes in the same PR. Although, personally I think it'd be really awesome to build a GitHub Action that if it sees that the WASM file has changed, it generates it's own WASM file from the commit shown, and if these files are exactly the same, then it passes.

Having a GitHub Action has the added benefit of solidly documenting the exact method needed to generate the WASM files themselves, which could be helpful in the future.

**Comment by savetheclocktower** [comment] 2023-09-22 23:50
> From your perspective, do you think it's enough to confirm that if the WASM file has changed, and the commit used has changed then everything's good? Or would we want to confirm that the commit being used is able to generate the WASM file exactly?

The first one. The second would require that we put the Emscripten toolchain into a GitHub Action, and that's just not worth the headache.

If not for needing to set up that toolchain, generating WASM files would be as simple as `tree-sitter build-wasm` from any parser repo's root. [This document](https://github.com/sogaiu/ts-questions/blob/master/questions/which-version-of-emscripten-should-be-used-for-the-playground/README.md) is what helped me figure that out, but lots of people use Docker instead, so in order to document this properly I'll probably need to dabble with the Docker side of things.

**Comment by confused-Techie** [comment] 2023-09-22 23:53
@savetheclocktower That sounds perfectly fine by me. Great point about having an overkill toolchain to do this. But glad to see some linked documentation, if we find we ever need to document the whole process of generating these files, although I'll assume this documentation has been mentioned or is already written elsewhere.

Otherwise, I'll happily put together a PR that can ensure the WASM file is being updated along with whatever key from the grammar file we decide.

What do we think of something like `grammarSource` as the key for storing this data?

**Comment by savetheclocktower** [comment] 2023-09-23 00:19
Let's do `parserSource` and make it in the style of whatever NPM will accept as a dependency value. That could be a bare version number (assumed to be available in NPM), a repo+sha (most common), or a repo+tag.

I was going to say that it was enough to give a simple SHA, since the name of the parser is already captured in the `parser` key, but that field just relies on `require` semantics and wouldn't be able to tell which repo the parser came from. (We shouldn't touch that field anyway for backward compatibility.)

Instead, we can do something like

```coffeescript
parserSource: "github:tree-sitter/tree-sitter-bash#fd4e40dab883d6456da4d847de8321aee9c80805"
```

which would give us the flexibility to pin to a SHA or a tag. It would also let us fork parsers where appropriate (as rarely as possible, of course) and point to our own forks.

And it would allow us to automate some of the WASM-file-building in the future.

**Comment by confused-Techie** [comment] 2023-09-23 00:23
Love this, absolutely fantastic! And great idea to just let the field be anything acceptable via NPM. Since like you said gives us the chance for more automation in the future.

In that case, knowing the key, I'll try to get to some checks we can do this weekend, so that we can make sure this always happens in the future. But glad we are both on board with the idea!

**Closed** 2023-10-15 19:44 UTC
Labels: bug

**Comment by danfuzz** [comment] 2023-10-16 17:51
Thanks so much for all the work on this.

Not that this should prevent this issue from staying closed, but I do want to note that the original source file that prompted me to file it unfortunately still causes the parser to choke, though now in a new and exciting way (it fails to mark up any syntax at all).

I intend to poke around the new code to see if I can help more directly, but in the meantime here's a new minimal example of the breakage:

```bash
#!/bin/bash

function x {
    x 2>x
}

function x {
    case x in
        --*) : ;;
    esac
}
```

And FWIW, here's the actual file I distilled that from: <https://github.com/danfuzz/milky-cloud/blob/51223615217161b1f4cf1e8768e50b2ba8720320/scripts/lib/milky-cloud/instance/wait-until-responsive>
