### ISSUE TITLE
Linux builds do not work on systems with CUPS disabled

### ISSUE THREAD

**Issue by hogsmead** [pulsar-edit/pulsar#410] opened 2023-03-02 13:20 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

When I try to launch Pulsar with the AppImage it gives me the following error:
`/tmp/.mount_Linux.SVMBLq/pulsar: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory`

### Pulsar version

1.102.0

### Which OS does this happen on?

❓ Other(Please specify in the OS details field below)

### OS details

Gentoo

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Have a Gentoo installation with `USE="-cups"` in your `make.conf`
2. Try to launch Pulsar

**Comment by Spiker985** [comment] 2023-03-02 15:42
Looks like libcups is responsive for printing. CUPS being [Common Unix Printing System](https://en.wikipedia.org/wiki/CUPS).

Ideally, the editor should be able to simply disable features if it doesn't find appropriate libraries (outside of core functionality).

But the irony is that I don't believe Pulsar (and by further extension Atom) actually _have_ printing capabilities to begin with (at least not in any menus)

It appears this is a functionality of electron, which you can confirm by opening DevTools and typing `window.print()` and you'll get a print dialog. Maybe there's a feature flag for electron to disable printing?

**Comment by Spiker985** [comment] 2023-03-02 15:47
This is further confirmed via the [electron build instructions](https://www.electronjs.org/docs/latest/development/build-instructions-linux) where the various `libcup*` libraries per distro are listed

**Comment by confused-Techie** [comment] 2023-03-04 05:59
Yeah looking into this, I can't see any way we are able to control this.

As fair as I'm able to find out, chromium itself actually requires cups to be there, with Electron inheriting this, and thus all Electron based applications.

So if there's no way for us to change this, then we should likely update our docs to include the installation of cups to be able to close this issue.

**Comment by icecream17** [comment] 2023-03-04 14:34
Mentioning https://github.com/electron/electron/issues/31151

**Comment by confused-Techie** [comment] 2023-03-06 00:07
What does @pulsar-edit/core & @pulsar-edit/documentation think of including this in our docs and closing the issue?

Through all the research I can find this seems to be a dependency of Electron with no way for us to disable. Most other similar issues have been closed as saying it's an issue upstream

**Comment by DeeDeeG** [comment] 2023-03-06 00:27
Hmm, yeah . If it's all the way in what sounds like C/C++ code from Chromium, and Electron/Chromium have no toggles we can flip about it, then I do think it's out of our hands.

@confused-Techie this seems like a fairly niche issue, but I suppose I'm not against us documenting it as a known issue.

**Comment by DeeDeeG** [comment] 2023-03-06 00:34
For what it's worth, there are several other shared object `.so` libraries needed for the program to even launch, though these seem to be present on most systems outside of super-minimal environments like certain Docker images. (Or in this issue's case, we have a fairly common Linux desktop feature configured off in Gentoo.)

**Comment by confused-Techie** [comment] 2023-03-06 00:36
> For what it's worth, there are several other shared object `.so` libraries needed for the program to even launch, though these seem to be present on most systems outside of super-minimal environments like certain Docker images. (Or in this issue's case, we have a fairly common Linux desktop feature configured off in Gentoo.)

You make a good point. Maybe this would be good to include in an advanced installation section, or a troubleshooting installation, rather than be shown to everyone that tries to download like the signed binaries issue

**Comment by confused-Techie** [comment] 2023-04-05 00:36
So sorry to say I'm going to go ahead and close this one.

Further research into the topic has confirmed that CUPS is required because of Electron, which requires it because of Chromium.

And a user did submit an issue to Chromium about having this as an optional dependency and it was closed as `WONTFIX`.

So while I don't see why this can't exist we aren't in the position to resolve the issue in any way.

Hopefully in the future this won't be an issue or it can otherwise be worked around client side, but I think the best thing we can do is state in some advanced installing section that CUPS is required.

* [Electron Issue](https://github.com/electron/libchromiumcontent/issues/60#issuecomment-51182108)
* [Chromium Issue Closed as WONTFIX](https://bugs.chromium.org/p/chromium/issues/detail?id=148984)

**Closed by confused-Techie** 2023-04-05 00:36 UTC
Labels: bug
