### ISSUE TITLE
fatal error: conio.h: No such file or directory 

### ISSUE THREAD

**Issue by abacik04** [pulsar-edit/pulsar#395] opened 2023-02-23 15:56 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

how can i download conio.h file to linux mint.
I am working in c language
It gives this error when I run it. Please help, how do I install it?

### Pulsar version

1.102.0

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

linux mint 

### Which CPU architecture are you running this on?

None

### What steps are needed to reproduce this?

I don't know.
I

### Additional Information:

Downloaded as flatpak(flathub)
I'm new at this
I'm just trying to learn programming language

**Comment by Daeraxa** [comment] 2023-02-23 23:31
Do you have the same error with any of the supported binaries such as the appimage, tarball or deb? We don't support the flatpak version.

**Comment by abacik04** [comment] 2023-02-24 05:38
OK:(


24 Şub 2023 Cum ÖÖ 2:31 tarihinde Daeraxa ***@***.***> şunu
yazdı:

**Comment by confused-Techie** [comment] 2023-02-24 06:21
@abacik04 To expand on what @Daeraxa was saying, the Flatpak binary is maintained by a member of the community, rather than officially by anyone from Pulsar. So it's recommended to temporarily try installing Pulsar via another method we officially release, like the AppImage, Tarball, or Deb. If those present the same issue, then we would be more than happy to look into as it's an issue within Pulsar.

If the issue doesn't happen there, then it's an issue of how it was packaged for FlatPak. Which you'd want to then file an issue with the community member that maintains that, over [here](https://github.com/flathub/dev.pulsar_edit.Pulsar).

**Comment by confused-Techie** [comment] 2023-03-12 04:27
@abacik04 Where you ever able to test and find out if this is an issue with Pulsar itself or the Flatpak distribution? We'd be more than happy to try and determine what the issue is once we know we are able to fix it

**Comment by confused-Techie** [comment] 2023-03-26 12:13
@abacik04 Again, just checking in, any update? We need more information to help resolve the issue here.

Otherwise @pulsar-edit/core how do we feel about closing this one? It's been a month since we last heard the op, without enough detail to do anything with it.

**Comment by abacik04** [comment] 2023-03-26 15:01
I'll check and see what I can findGalaxy cihazımdan gönderildi
-------- Orijinal mesaj --------Kimden: confused_techie ***@***.***> Tarih: 26.03.2023  3:13 PM  (GMT+03:00) Alıcı: pulsar-edit/pulsar ***@***.***> Cc: abacik04 ***@***.***>, Mention ***@***.***> Konu: Re: [pulsar-edit/pulsar] fatal error: conio.h: No such file or directory  (Issue #395) 
@abacik04 Again, just checking in, any update? We need more information to help resolve the issue here.
Otherwise @pulsar-edit/core how do we feel about closing this one? It's been a month since we last heard the op, without enough detail to do anything with it.

**Closed** 2023-04-06 19:00 UTC
Labels: bug

**Comment by confused-Techie** [comment] 2023-04-06 19:19
@abacik04 Where you able to find a resolution?
