### ISSUE TITLE
No Commandline Response

### ISSUE THREAD

**Issue by ElectronicsArchiver** [pulsar-edit/pulsar#257] opened 2022-12-24 01:51 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I get absolutely no response / output when typing for example

```sh
pulsar --help
pulsar --package install
pulsar -p help install
```

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Kubuntu 22.04

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

1. Open terminal
2. Type one of the commands

### Additional Information:

Installed Pulsar from a deb file.

**Comment by DeeDeeG** [comment] 2022-12-25 08:02
Can you try this and see if it works?

> `/opt/Pulsar/pulsar --no-sandbox`

**Comment by ElectronicsArchiver** [comment] 2022-12-25 09:49
@DeeDeeG

```sh
/opt/Pulsar/pulsar --no-sandbox --help
```

works

```sh
/opt/Pulsar/pulsar --no-sandbox --package
```

and their variations, don't, no output at all.

**Comment by DeeDeeG** [comment] 2022-12-25 12:13
What is the version of Pulsar you have installed?

`/opt/Pulsar/pulsar --no-sandbox --version`

I can see if I can reproduce the issue with that version, or you can try the beta or latest Cirrus binary.

---

`/opt/Pulsar/pulsar --no-sandbox --package` prints the `ppm` help message for me.

Works for me on Pulsar 1.63.2022112111 (a build from last month, on Ubuntu 22.04/Linux Mint), or Pulsar 1.100.2022122013 (a build from a few days ago, on macOS 10.15 "Catalina").

<details>

```console
$ /opt/Pulsar/pulsar --no-sandbox --package

Pulsar Package Manager powered by https://pulsar-edit.com

  Usage: apm <command>

  where <command> is one of:
      ci, clean, config, dedupe, deinstall, delete, dev, develop, disable, docs,
    enable, erase, featured, home, i, init, install, link, linked, links, list,
    ln, lns, login, ls, open, outdated, prune, publish, rebuild,
    rebuild-module-cache, remove, rm, search, show, star, starred, stars, test,
    uninstall, unlink, unpublish, unstar, update, upgrade, view.

  Run `apm help <command>` to see the more details about a specific command.

Options:
  --color        Enable colored output                 [boolean] [default: true]
  -v, --version  Print the apm version
  -h, --help     Print this usage message

  Prefix an option with `no-` to set it to false such as --no-color to disable
  colored output.
```

</details>

**Comment by ElectronicsArchiver** [comment] 2022-12-25 12:52
```
Pulsar  : 1.100.2022122218
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
```

**Comment by DeeDeeG** [comment] 2022-12-28 04:52
- You were using the .deb from this CI run: https://cirrus-ci.com/task/6489945565560832 based on this commit: https://github.com/pulsar-edit/pulsar/commit/6fcaafb70bc7e6ac248d4bc0b1fd083e3c3fb94b
  - I can reproduce the issue with the .deb from this CI run :x:
- I believe this commit fixed the issue: https://github.com/pulsar-edit/pulsar/commit/c2cdb6926aabec8c0f16f6f4719de9898136e6a7 (See the .deb from this CI run: https://cirrus-ci.com/task/6273398280552448)
  - `pulsar --help` and `pulsar --package` seems to work properly now. :heavy_check_mark: 

---

Please try the latest binaries from Cirrus, if you don't mind. I believe https://github.com/pulsar-edit/pulsar/pull/269 fixed this issue.

https://pulsar-edit.dev/download.html#cirrus-ci-binaries

**Comment by ElectronicsArchiver** [comment] 2022-12-28 09:32
I installed the latest CI
```
Pulsar  : 1.100.2022122803
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
```

while the help command works with pulsar

```sh
pulsar --help
```

the packaging commands still don't


```sh
pulsar --package
```

**Comment by mauricioszabo** [comment] 2023-01-02 16:32
It's fixed on the latest build - 1.100.2023010119.

Tested both when Pulsar have no window open, and when it does have one, and two windows open. If you still see this problem, please reopen this ticket and we'll try to reproduce it.

**Closed by mauricioszabo** 2023-01-02 16:32 UTC
Labels: bug, linux

**Comment by ElectronicsArchiver** [comment] 2023-01-02 18:43
@mauricioszabo 

Updated to the lastest `.deb` CI build

```
Pulsar  : 1.100.2023010119
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
```

but the package command still does nothing.

**Comment by DeeDeeG** [comment] 2023-01-04 04:17
It is working for me

```console
$ pulsar --version
Pulsar  : 1.100.2023010400
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0

$ ppm --version
apm  2.7.0
npm  6.14.17
node 16.0.0 x64
atom 1.100.2023010400
python 
git 2.34.1

$ pulsar --package

Pulsar Package Manager powered by https://pulsar-edit.com

  Usage: pulsar --package <command>

  where <command> is one of:
[ . . . snipped . . . ]

$ ls -lh /usr/bin/pulsar /usr/bin/ppm
lrwxrwxrwx 1 root root   37 Jan  3 /usr/bin/ppm -> /opt/Pulsar/resources/app/ppm/bin/apm
-rwxr-xr-x 1 root root 5.3K Jan  3 /usr/bin/pulsar
```

Linux Mint 21.0 "Vanessa", based on Ubuntu 22.04.

You can call `/opt/Pulsar/resources/app/ppm/bin/apm` directly for now, if you need to work around it.

I wonder if it's somehow a KDE thing? Are you using an unusual shell? Does calling `ppm` directly work?

**Comment by ElectronicsArchiver** [comment] 2023-01-04 09:54
@DeeDeeG 

1. You are on a later build, I updated again now:

```
Pulsar  : 1.100.2023010403
Electron: 12.2.3
Chrome  : 89.0.4389.128
Node    : 14.16.0
```

2. `--package` still has no output 
   ( also no output with options that work with `ppm`, see below )

3. I'm using Konsole, so no, nothing special.

4. `opt/..` and `ppm` now work:

```
Pulsar Package Manager powered by https://pulsar-edit.com

  Usage: pulsar --package <command>

  where <command> is one of:
      ci, clean, config, dedupe, deinstall, delete, dev, develop, disable, docs,
    enable, erase, featured, home, i, init, install, link, linked, links, list,
    ln, lns, login, ls, open, outdated, prune, publish, rebuild,
    rebuild-module-cache, remove, rm, search, show, star, starred, stars, test,
    uninstall, unlink, unpublish, unstar, update, upgrade, view.

  Run `pulsar --package help <command>` to see the more details about a specific command.

Options:
  --color        Enable colored output                                     [boolean] [default: true]
  -v, --version  Print the ppm version
  -h, --help     Print this usage message

  Prefix an option with `no-` to set it to false such as --no-color to disable
  colored output.
```

Which is great, though that still doesn't explain why it doesn't show with `--package` ..

**Comment by Daeraxa** [comment] 2023-01-04 10:42
`--package` was working for me from the .deb on MX Linux when I tested a binary just the other day (1.100.2022122803).

**Comment by mauricioszabo** [comment] 2023-01-04 20:37
I'm also on KDE and Konsole, so.... I have no idea...
