### ISSUE TITLE
Strange "half screen" error in editor

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/pulsar#191] opened 2022-12-03 04:07 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Does your issue already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?
See gif below.
The screen "splits" within the editor causing a visual error and strange scrolling behaviour and a horizontal scrollbar in the wrong place.
![gifgit](https://user-images.githubusercontent.com/58074586/205422449-c4aea1eb-803c-4260-9348-cbd21ffba09b.gif)

### Which OS does this happen on?

🐧 Debian based (Linux Mint, Ubuntu, etc.)

### OS details

Linux Mint 20.3

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

I haven't been able to replicate this as such. The file itself is an untitled file with content. I had a ton of tabs open and was clicking rapidly to close the ones I didn't want and this error showing on this tab.

(I had to lie about replicating in safe mode as I can't reliably replicate this yet I've seen it a few times).

### Additional Information:

Dev version commit f4dfa048c

This is apparently an old Atom bug that is yet to be resolved and is difficult to replicate reliably. Logging it so we can keep track and refer any duplicates.

[Discord conversation](https://discord.com/channels/992103415163396136/992103415163396139/1048428650107764796).

Console logs checked but nothing of relevance.

HTML of the editor pane attached.
[bug_html.txt](https://github.com/pulsar-edit/pulsar/files/10145585/bug_html.txt)

**Comment by bobemoe** [comment] 2023-03-05 10:14
Do you think this is related to your other issue? https://github.com/pulsar-edit/pulsar/issues/355

I am seeing the misplaced scroll bar I think you describe while reproducing the other issue:

![image](https://user-images.githubusercontent.com/2304970/222954307-1a0a5c1a-a5bd-49e0-9ab7-77edab06c2a8.png)

**Comment by Daeraxa** [comment] 2023-03-05 15:02
I very much think it is... I forgot I even opened this without having replication steps...

**Comment by savetheclocktower** [comment] 2023-07-06 21:16
The workaround that I use on this one is to select all text, cut, and paste.

My fear is that this is something deep in `text-buffer` code. The abstraction we're presenting of ordinary monospace text inside a `div` with `overflow: auto` is, well, a lie; the horizontal and vertical scrollbars are in separate `div`s from the content, and scrolling the buffer just updates a `transform: translate(x, y)` on the element with the text in it.

That means that any operation that changes the buffer text results in some amount of math to estimate the buffer height and buffer width. Height would ordinarily be easy — (number of lines) times (line height) — but is much harder if soft wrap is enabled. My low-confidence guess is that something is going wrong in this measurement phase.

**If this is happening to you, here are two requests:**

1. If you're experiencing this and are able to reproduce it on some non-sensitive text, please comment on this ticket with _exact_ reproduction steps, and we'll be quite grateful.
2. If you've unchecked the **Soft Wrap** option _and this is still happening for you_, please add a comment to this ticket. If this were occurring in the absence of soft wrap, it would disprove the hunch explained above.

**Comment by bobemoe** [comment] 2023-08-26 09:07
Sorry for the delay, I was going to reply when your first requested, so I went to reproduce the issue with my known method documented in #355 (yes I'm still using the same version 1.102.0) and I couldn't make it happen!  I was probably using a different file but I thought it was the method not the content. Maybe its both. Anyway, its just happened to me again... 

I always work with a project folder open inside a git repo, however to keep things simple I just closed my project folder and tested this in a new even unsaved tab and still reproduced it:

1. open a new pulsar tab, paste in the file, you dont even need to save it or select the code type
2. IMPORTANT: scroll up, the bug seems not to be triggered if you are right at the very bottom.
3. select all (ctrl-a)
4. auto indent (ctrl-shift-p Auto Indent)

The misalignment appears. The workaround:

5. select all (ctrl-a)
6. cut (ctrl-x)
7. paste (ctrl-v)

Now the misalignment has gone.

You can repeat this loop by going back to step 2.

Some things to note:

The file is longer than my screen so there is vertical scroll, the file is quite short so for those of you with big screens you may get no scroll and I would guess this will make a difference?

I have tried both with and without **soft wrap**: same outcome. All lines are quite short so even when enabled no wrapping actually happens.

Interesting this time if I go back to step 2 I don't have to un-indent anything before indenting. When in my project, after the indent the blank lines are marked as changed, as if a white space has been removed, once saved these disappear, but after that git doesn't say the file has actually changed.

This was all on 1.102.0 but I've just updated to 1.108.0 and still seeing the same thing.

```
#ifndef SIM_H
#define SIM_H

class Sim{
public:
    float fuel=0;
private:
    int torq=0;
    int rpm=0;
    float temp=25;
    int error=0;

    bool running=false;

    unsigned long runfor=0;
    unsigned long stopfor=0;

    float increase(float val, float upper) {
        if (val < upper) {
            val += 1.0; // You can adjust the increment as needed
        }
        // Apply exponential slowdown as val approaches the upper limit
        float slowdownFactor = 1.0 / (1.0 + exp(0.1 * (upper - val)));
        val += 10.0 * slowdownFactor; // Adjust the factor for the rate of slowdown
        return val;
    }

    float decrease(float val, float upper) {
        if (val > lower) {
            val -= 1.0; // You can adjust the decrement as needed
        }
        // Apply exponential slowdown as val approaches the lower limit
        float slowdownFactor = 1.0 / (1.0 + exp(0.1 * (val - lower)));
        val -= 10.0 * slowdownFactor; // Adjust the factor for the rate of slowdown
        return val;
    }

public:
    void begin(){
    }

    void loop(){
        int tmp;
        if(running){
            tmp=fuel+random(-5,6);
            fuel = constrain(tmp, 10, 200);
            tmp=torq+random(-15,16);
            torq = constrain(torq, 10, 200);
            rpm = fuel + torq;
            temp=increase(temp,80);
        }else{
            rpm=0;
            fuel=0;
            temp=decrease(temp,25);
        }
        comms.write("e.fuel=%d");
    }
};
#endif
```

**Comment by catscarlet** [comment] 2023-10-26 16:04
I didn't check **Soft Warp** but this still happened to me today.

Video link: https://youtu.be/_s_ppATKMEI

I'm a Linux Mint 20.3 user too.
Pulsar 1.108.0x64

I feel like, this bug exists since even Atom was young, and it happens both on Win7 and Linux(I'm using it since Mint 18).
This happens very infrequently to me, and I have no idea how to re-produce it, but it does exist.

**Comment by catscarlet** [comment] 2023-10-26 16:29
Also, more research and it feels like,it's not the bottom is not covered by something, but the **view scope** moved to the wrong position.

Like this:

![screenshot_on_b85m_by_flameshot_at_2023-10-27_00-17-46](https://github.com/pulsar-edit/pulsar/assets/10594035/111b7a4b-a20d-4778-8c42-eb811af86024)

Here is the video link: https://www.youtube.com/watch?v=2Rw6FKbm5Ds

See when I moved the indicator(I mean the text cursor), the content moved like the view scope 's (0px,0px) was not the editor's (0px,0px), more like on the editor, like (0px, -300px).




Also the number of the lines are misplaced/dislocated. I don't remember what number my code is but I'm sure it's the the right number on screen.

**Comment by asiloisad** [comment] 2023-11-01 16:33
this issue may be related https://github.com/atom/line-top-index/issues/3

**Comment by confused-Techie** [comment] 2023-11-02 00:11
@asiloisad An interesting find that may help to point where this occurs

**Comment by confused-Techie** [comment] 2023-11-11 01:51
@asiloisad Seriously impressive work!
This is amazing you were able to track it down so well!

**Comment by asiloisad** [comment] 2023-11-12 08:08
a quick (but not complete) fix of issue and proof the last cursor is culprit. paste it to `init.js`

```javascript
atom.workspace.getCenter().onWillDestroyPane((pane) => {
  for (let pane of atom.workspace.getCenter().getPanes()) {
    let item = pane.getActiveItem()
    if (!atom.workspace.isTextEditor(item)) { continue }
    item.dummyCursor = item.addCursorAtBufferPosition([0,0])
  }
})

atom.workspace.getCenter().onDidDestroyPane((pane) => {
  for (let pane of atom.workspace.getCenter().getPanes()) {
    let item = pane.getActiveItem()
    if (!atom.workspace.isTextEditor(item)) { continue }
    if (item.dummyCursor) {
      item.dummyCursor.destroy() ; delete item.dummyCursor
    }
  }
})
```

**Comment by asiloisad** [comment] 2023-11-12 08:39
a temporary fix, paste to `init.js`:

```javascript
atom.workspace.getCenter().onWillDestroyPane(() => {
  for (let pane of atom.workspace.getCenter().getPanes()) {
    let item = pane.getActiveItem()
    if (!atom.workspace.isTextEditor(item)) { continue }
    item.dummyCursor = item.addCursorAtBufferPosition([0,0])
    item.dummyTop = item.component.scrollTop
  }
})

atom.workspace.getCenter().onDidDestroyPane(() => {
  for (let pane of atom.workspace.getCenter().getPanes()) {
    let item = pane.getActiveItem()
    if (!atom.workspace.isTextEditor(item)) { continue }
    if (item.dummyCursor) {
      item.dummyCursor.destroy() ; delete item.dummyCursor
      item.component.scrollTop = item.dummyTop
    }
  }
})
```

**Comment by asiloisad** [comment] 2023-11-12 22:19
a new quick-fix, paste it to `init.js`. It force to place hidden cursor always at [0,0], instead of placing it at last cursor position

```js
function updateCursorsToRender() {
  this.decorationsToRender.cursors.length = 0;

  this.decorationsToMeasure.cursors.forEach(cursor => {
    const { screenPosition, className, style } = cursor;
    const { row, column } = screenPosition;

    const pixelTop = this.pixelPositionAfterBlocksForRow(row);
    const pixelLeft = this.pixelLeftForRowAndColumn(row, column);
    let pixelWidth;
    if (cursor.columnWidth === 0) {
      pixelWidth = this.getBaseCharacterWidth();
    } else {
      pixelWidth = this.pixelLeftForRowAndColumn(row, column + 1) - pixelLeft;
    }

    const cursorPosition = {
      pixelTop,
      pixelLeft,
      pixelWidth,
      className,
      style
    };
    this.decorationsToRender.cursors.push(cursorPosition);
    // if (cursor.isLastCursor) this.hiddenInputPosition = cursorPosition;
  });
}

atom.workspace.observeTextEditors((editor) => {
  editor.component.updateCursorsToRender = updateCursorsToRender.bind(editor.component)
})
```

**Comment by savetheclocktower** [comment] 2023-11-13 00:44
A breakthrough, we think.

When this is happening to you, run this in your developer console:

```js
atom.workspace.getActiveTextEditor().getElement().querySelector('.scroll-view').scrollTop
```

It'll return a number greater than 0.

As far as I can tell, this number should _never_ be greater than 0.

To receive keyboard events, the text editor component uses a hidden `input` element. This element is the one that always has focus in the active text editor. The position of this hidden input tracks the position of the last (or only) cursor in the editor.

The way to trigger this bug, generally speaking, is this:

1. Arrange your text editor so that the cursor is outside the current viewport — e.g., put the cursor at the bottom of the file, then scroll up until you can't see it anymore.
2. Do something that causes the editor to lose focus — e.g., open the file finder or the command palette.
3. Return focus to the editor — e.g., hit <kbd>Esc</kbd> from the palette you just opened.
 
At this point, your editor will be borked, but you can fix it in the console like so:

```js
atom.workspace.getActiveTextEditor().getElement().querySelector('.scroll-view').scrollTop = 0
```

There is some sort of implicit behavior here that is forcing `div.scroll-view` to scroll. This shouldn't ever happen because, despite its name, `div.scroll-view` has `overflow: hidden`. The text editor actually “scrolls” by receiving scroll events from the “dummy” vertical/horizontal scrollbars and setting a corresponding `translateY` and `translateX` on a child of `div.scroll-view`.

So we think this is happening because the browser wants to implicitly put the hidden text input back into view whenever an editor is re-focused.

@asiloisad has proposed that we don't need the hidden input to follow the cursor. If we keep it positioned at (0, 0), then none of this happens — presumably because, when the editor is re-focused, the hidden input is already “in view,” so the browser doesn't need to move anything. I'm cautiously supportive of this, but I'd still like to understand why the Atom developers made it so that the hidden input follows the cursor. Changing that behavior feels like it _could_ be consequential, but I have no evidence of that yet. We'll see if that change has any surprising side effects for @asiloisad in the next few days.

_If_ we found that the hidden input tracks the cursor position for a specific and wise reason, then we could compromise by moving the hidden input to (0, 0) on editor blur, then restoring it to the cursor position once the editor is re-focused.

Another possible fix: [this code snippet](https://github.com/pulsar-edit/pulsar/blob/master/src/text-editor-component.js#L1812-L1825) is one example of a scenario where `scrollContainer.scroll(Top|Left)` are being explicitly reset to `0`. If we could identify all the troublesome code paths, we could add explicit `scroll(Top|Left)` resets in those places. This would be a much hackier fix, and I'd prefer to avoid it; but that's a code change that carries less of a chance of regressions.

**Comment by savetheclocktower** [comment] 2023-11-13 01:01
Found the [PR that introduced this bug](https://github.com/atom/atom/pull/20892/files) in its most recent form.

Atom used to explicitly reset the container's `scroll(Top|Left)` to `0` _whenever_ the hidden input received focus, but this PR assumed that that wouldn't be necessary anymore once all explicit calls to `this.getHiddenInput().focus()` were given the `preventScroll` option. That assumption seems to be in error!

This is now my favored fix just because it's a solution that was proven to work in the past. I might throw together a PR tonight.

**Comment by mauricioszabo** [comment] 2023-11-13 14:52
@asiloisad GREAT FREAKING JOB!!!

I have no words! I tried on a file, it didn't work, but then I found that if I closed all other tabs and had no docks active, I could 100% reproduce the error (well, except that in my case, the whole screen goes blank instead of "half size", but I also have a lot of customizations)

I am seriously excited for this bug to finally be fixed!

**Comment by savetheclocktower** [comment] 2023-11-13 17:42
> (well, except that in my case, the whole screen goes blank instead of "half size", but I also have a lot of customizations)

“Half screen” isn’t always accurate, but it ended up being a useful shorthand.

How much the screen moves depends on how far the cursor is from a visible edge of the viewport. If it’s _barely_ out of view, the browser will scroll the window just a little, and things will appear just a little off. If the cursor is at the bottom of a long file and you scroll to the top before triggering this issue, the browser will set `scrollTop` roughly equal to `$pixel_height_of_buffer - $pixel_height_of_viewport`, and the whole screen will go blank.

(This effect was _so mysterious_ for months, but it is _so mundane_ now that we understand exactly when and why it happens.)

**Closed** 2023-11-13 21:58 UTC
Labels: bug, needs-reproduction
