### ISSUE TITLE
Half of text-editor view is bugged sometimes

### ISSUE THREAD

**Issue by asiloisad** [pulsar-edit/pulsar#627] opened 2023-07-06 20:55 UTC
### Thanks in advance for your bug report!

- [X] Have you reproduced issue in [safe mode](https://pulsar-edit.dev/docs/atom-archive/faq/sections/what-does-safe-mode-do.html)?
- [X] Have you used the [debugging guide](https://pulsar-edit.dev/docs/atom-archive/hacking-atom/#debugging) to try to resolve the issue?
- [X] Have you checked our [FAQs](https://pulsar-edit.dev/docs/launch-manual/sections/faq/) to make sure your question isn't answered there?
- [X] Have you checked to make sure your issue does not already [exist](https://github.com/issues?q=is%3Aissue+user%3Apulsar-edit+is%3Aopen)?
- [X] Have you checked you are on the latest release of Pulsar?

### What happened?

I'm often encounter the bug that ~half of text editor is covered by highlight probably. I don't know how to reproduce this or which package produce it. Test in safe mode is hard, because problem occur in random time (from my perspective, but some actions trigger it probably). It's occur in any grammar (like Python, CSON, JavaScript). It look like highlight CSS class have to do with it.

Have has anyone met the same problem?

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/d84f4433-e376-4a49-975b-8c64fa6a211f)

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/b04ad633-d88b-419c-aa01-d85539cb84d4)

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/3b9b622b-d145-4fbf-8230-38983c10a8a9)

![image](https://github.com/pulsar-edit/pulsar/assets/29706474/7359a01c-a3a6-4c2b-ad93-9e41368ba1cd)

### Pulsar version

1.106.0

### Which OS does this happen on?

🪟 Windows

### OS details

10 22H2

### Which CPU architecture are you running this on?

64-bit(x86_64)

### What steps are needed to reproduce this?

I don't have a clue.

**Comment by savetheclocktower** [comment] 2023-07-06 21:03
Closing as duplicate of #191. But, yes, lots of us have noticed this.

I could've sworn that #191 contained repro steps, but if not then they're somewhere in the Discord history. I'll have to track them down at some point.

Failing that, if you do discover a way to reproduce this with arbitrary text content, please add a comment in that ticket. Thanks!

**Closed by savetheclocktower** 2023-07-06 21:03 UTC
Labels: bug

**Comment by Daeraxa** [comment] 2023-07-07 02:47
@savetheclocktower you may be thinking of the steps in https://github.com/pulsar-edit/pulsar/issues/355 which *might*(???) be related?

**Comment by asiloisad** [comment] 2023-07-07 02:57
I'm getting this error often during closing another tabs, because the main text editor change the width then -> soft-wrap coming in -> bug has appear. I think investigating soft-wrap is needed, as @savetheclocktower has mention in #191.

**Comment by asiloisad** [comment] 2023-07-07 03:03
![image](https://github.com/pulsar-edit/pulsar/assets/29706474/c7141efc-b9cb-42b1-b81e-df1bf8711e4b)
I might have a clue. Isn't strange that line number 336 if after 377?

**Comment by savetheclocktower** [comment] 2023-07-07 03:30
> @savetheclocktower you may be thinking of the steps in #355 which _might_(???) be related?

Nah, we had some good repro steps for this specific issue, but I was too busy with other stuff to open the can of worms. I'll find it eventually.
